import {MATCHES} from './data.js';
import {footmatePlatform} from './platform/application/platform.js';

const MATCHDAY_VERSION='4.5.1';
const MATCHDAY_STORAGE_KEY=footmatePlatform.storageKeys.matchday;
const matchdayRepository=footmatePlatform.repositories.matchday;
const allowed=new Set(['upcoming','matchday','checked-in','late','updated','canceled']);
const root=document.getElementById('footmate-next');
function session(){return footmatePlatform.session.read()||{}}
function currentMatchId(){return session().joinedMatchId||null}
function currentMatch(){const id=currentMatchId();return MATCHES.find(match=>match.id===id)||null}
function initial(){const stored=matchdayRepository.read({})||{},matchId=currentMatchId();if(stored.matchId===matchId&&allowed.has(stored.status))return stored;return {version:MATCHDAY_VERSION,matchId,status:'upcoming',arrival:'unknown',noticeSeen:false,updatedAt:new Date().toISOString()}}
let state=initial();
function persist(patch={}){state={...state,...patch,version:MATCHDAY_VERSION,matchId:currentMatchId(),updatedAt:new Date().toISOString()};matchdayRepository.write(state);enhance();return state}
function syncSession(patch={}){const next={...session(),...patch};footmatePlatform.session.write(next);return next}
function navigate(route){syncSession({route});location.reload()}
function statusCopy(status){return {upcoming:['경기 준비','경기 시작 20분 전부터 체크인할 수 있어요.'],matchday:['도착 준비','경기장 도착 상태를 확인하고 체크인을 완료해주세요.'],'checked-in':['체크인 완료','도착 확인이 끝났습니다. 팀 공지와 경기장 안내를 확인하세요.'],late:['늦을 것 같아요','도착 지연 상태를 저장했습니다. 운영자에게 전달되는 UX 계약을 시뮬레이션합니다.'],updated:['운영 변경 확인','변경 공지를 확인했습니다. 최신 안내를 기준으로 이동해주세요.'],canceled:['경기 취소','운영 취소 상태입니다. 참가비 반환과 대체 경기 탐색 흐름을 확인할 수 있습니다.']}[status]||['경기 준비','경기 정보를 확인하세요.']}
function panel(){const [title,copy]=statusCopy(state.status);const primary=state.status==='upcoming'?'<button type="button" data-matchday-action="arrive">도착 상태 알리기</button>':state.status==='matchday'||state.status==='late'?'<button type="button" data-matchday-action="checkin">체크인 완료</button>':state.status==='canceled'?'<button type="button" data-matchday-action="find">다른 경기 찾기</button>':'<button type="button" data-matchday-action="notice">공지 다시 보기</button>';return `<section class="fm-matchday-panel" data-matchday-version="${MATCHDAY_VERSION}" data-matchday-state="${state.status}" aria-label="경기 당일 운영"><div class="fm-matchday-kicker">MATCHDAY · ${MATCHDAY_VERSION}</div><div class="fm-matchday-status" role="status"><b>${title}</b><span>${copy}</span></div><div class="fm-matchday-grid"><article><small>체크인</small><b>킥오프 20분 전부터</b><span>이 프로토타입은 시간창과 도착 상태 계약만 검증합니다.</span></article><article><small>경기장 안내</small><b>메인 출입구 → 3층 코트</b><span>주소·동선은 샘플 안내이며 실시간 지도 연동이 아닙니다.</span></article><article><small>팀 공지</small><b>조끼는 현장 제공</b><span>메시지 전송 backend 없이 공지 확인 UX만 시뮬레이션합니다.</span></article></div><div class="fm-matchday-actions">${primary}${state.status!=='canceled'&&state.status!=='checked-in'?'<button type="button" data-matchday-action="late">늦을 것 같아요</button>':''}${state.status==='late'?'<button type="button" data-matchday-action="recover">도착 상태 수정</button>':''}${state.status!=='canceled'?'<button type="button" data-matchday-action="update">경기 변경 공지 보기</button>':''}</div><p class="fm-matchday-boundary">실시간 위치·지도·팀 채팅·알림 backend는 연결하지 않았습니다. 상태와 복구 흐름을 검증하는 deterministic simulation입니다.</p></section>`}
function myMatches(){const current=session(),match=currentMatch();if(!match)return `<section class="fm-next-section fm-next-my-matches" data-my-matches aria-label="내 경기"><div class="fm-next-section-head"><div><h2>내 경기</h2><p>참가한 경기를 MY에서 이어서 확인할 수 있어요.</p></div></div><div class="fm-next-empty">아직 참가한 경기가 없어요.<br>마음에 드는 경기를 찾아 참가해보세요.<div style="margin-top:16px"><button type="button" class="fm-next-button fm-next-button--primary" data-action="nav-discover">경기 찾기</button></div></div></section>`;const stage=current.matchStage||'upcoming';return `<section class="fm-next-section fm-next-my-matches" data-my-matches aria-label="내 경기"><div class="fm-next-section-head"><div><h2>내 경기</h2><p>경기 전부터 결과 확인까지 MY에서 이어집니다.</p></div></div><div class="fm-next-upcoming"><div class="fm-next-upcoming-top"><span>${stage==='matchday'?'TODAY':stage==='postgame'?'COMPLETED':'UPCOMING'}</span><span class="fm-next-upcoming-count">${match.dateLabel}</span></div><h2>${match.place}</h2><p>${match.address}</p><div class="fm-next-upcoming-actions"><button type="button" class="fm-next-button fm-next-button--lime" data-action="${stage==='matchday'?'check-in':'open-joined-match'}">${stage==='matchday'?'체크인':'경기 상세'}</button><button type="button" class="fm-next-button fm-next-button--secondary" data-action="team-chat">팀 메시지</button></div></div><div class="fm-next-status-list"><div class="fm-next-status-card is-current"><span class="fm-next-status-icon"><svg class="fm-next-icon" viewBox="0 0 24 24" aria-hidden="true"><rect x="4" y="5.5" width="16" height="14" rx="2"/><path d="M8 3.5v4M16 3.5v4M4 10h16"/></svg></span><div><b>${stage==='postgame'?'경기 완료':'참가 확정'}</b><p>${stage==='postgame'?'경기 결과와 평가가 저장됐어요.':'경기 정보 변경이 있으면 이 화면에서 바로 알려드려요.'}</p></div></div><div class="fm-next-status-card${stage==='matchday'?' is-current':''}"><span class="fm-next-status-icon"><svg class="fm-next-icon" viewBox="0 0 24 24" aria-hidden="true"><path d="M12 21s6-5.1 6-11a6 6 0 1 0-12 0c0 5.9 6 11 6 11Z"/><circle cx="12" cy="10" r="2"/></svg></span><div><b>경기 당일</b><p>경기 20분 전부터 체크인과 길찾기를 바로 사용할 수 있어요.</p></div></div><div class="fm-next-status-card${stage==='postgame'?' is-current':''}"><span class="fm-next-status-icon"><svg class="fm-next-icon" viewBox="0 0 24 24" aria-hidden="true"><path d="M5 19v-5M12 19V9M19 19V4"/></svg></span><div><b>경기 후</b><p>간단한 평가와 경기 레벨 변화가 다음 추천에 반영됩니다.</p></div></div></div></section>`}
function homeStrip(){const [title,copy]=statusCopy(state.status);return `<div class="fm-matchday-home" data-matchday-home data-matchday-state="${state.status}"><small>MATCHDAY OPERATIONS</small><b>${title}</b><span>${copy}</span><button type="button" data-matchday-action="profile">MY에서 내 경기 보기</button></div>`}
function simplifyNav(){for(const nav of root?.querySelectorAll('.fm-next-nav')||[]){nav.querySelector('[data-action="nav-schedule"]')?.remove();nav.style.gridTemplateColumns='repeat(3,minmax(0,1fr))'}}
function enhanceMy(){const profile=root?.querySelector('[data-screen="profile"]');if(!profile)return;let section=profile.querySelector('[data-my-matches]');const html=myMatches();if(!section){const topbar=profile.querySelector('.fm-next-topbar');if(topbar)topbar.insertAdjacentHTML('afterend',html)}else{const joined=section.dataset.joinedMatchId||'';const expected=currentMatchId()||'';if(joined!==expected)section.outerHTML=html}section=profile.querySelector('[data-my-matches]');if(section)section.dataset.joinedMatchId=currentMatchId()||'';if(section&&currentMatchId()){const existing=section.querySelector('[data-matchday-version]');if(!existing)section.insertAdjacentHTML('beforeend',panel());else if(existing.dataset.matchdayState!==state.status)existing.outerHTML=panel()}}
function enhance(){state=initial();simplifyNav();enhanceMy();const schedule=root?.querySelector('[data-screen="schedule"]');if(schedule&&currentMatchId()){schedule.setAttribute('data-matchday-module-version',MATCHDAY_VERSION);const existing=schedule.querySelector('[data-matchday-version]');if(!existing){const target=schedule.querySelector('.fm-next-section')||schedule;target.insertAdjacentHTML('afterbegin',panel())}else if(existing.dataset.matchdayState!==state.status)existing.outerHTML=panel()}const home=root?.querySelector('[data-screen="home"]');if(home&&currentMatchId()){const existing=home.querySelector('[data-matchday-home]');if(!existing){const context=home.querySelector('.fm-next-context-card');if(context)context.insertAdjacentHTML('afterend',homeStrip())}else if(existing.dataset.matchdayState!==state.status)existing.outerHTML=homeStrip()}}
document.addEventListener('click',event=>{const scheduleTarget=event.target.closest('[data-action="nav-schedule"]');if(scheduleTarget){event.preventDefault();event.stopPropagation();navigate('profile');return}const target=event.target.closest('[data-matchday-action]');if(!target)return;event.preventDefault();const action=target.dataset.matchdayAction;if(action==='arrive'){persist({status:'matchday',arrival:'on-the-way'});return}if(action==='checkin'){persist({status:'checked-in',arrival:'arrived'});const id=currentMatchId();syncSession({checkedInMatchId:id,matchStage:'matchday'});enhance();return}if(action==='late'){persist({status:'late',arrival:'late'});return}if(action==='recover'){persist({status:'matchday',arrival:'on-the-way'});return}if(action==='update'){persist({status:'updated',noticeSeen:true});return}if(action==='notice'){persist({noticeSeen:true});return}if(action==='find'){navigate('discover');return}if(action==='profile'){navigate('profile');return}},true);
const observer=new MutationObserver(enhance);if(root)observer.observe(root,{childList:true,subtree:true});window.__FOOTMATE_MATCHDAY__={version:MATCHDAY_VERSION,storageKey:MATCHDAY_STORAGE_KEY,read:()=>initial(),setStatus:(status,patch={})=>allowed.has(status)?persist({status,...patch}):initial(),reset:()=>{matchdayRepository.clear();state=initial();enhance();return state}};enhance();