import {footmatePlatform} from './platform/application/platform.js';

const MATCHDAY_VERSION='4.5.0';
const MATCHDAY_STORAGE_KEY=footmatePlatform.storageKeys.matchday;
const matchdayRepository=footmatePlatform.repositories.matchday;
const allowed=new Set(['upcoming','matchday','checked-in','late','updated','canceled']);
const root=document.getElementById('footmate-next');
function session(){return footmatePlatform.session.read()||{}}
function currentMatchId(){return session().joinedMatchId||null}
function initial(){const stored=matchdayRepository.read({})||{},matchId=currentMatchId();if(stored.matchId===matchId&&allowed.has(stored.status))return stored;return {version:MATCHDAY_VERSION,matchId,status:'upcoming',arrival:'unknown',noticeSeen:false,updatedAt:new Date().toISOString()}}
let state=initial();
function persist(patch={}){state={...state,...patch,version:MATCHDAY_VERSION,matchId:currentMatchId(),updatedAt:new Date().toISOString()};matchdayRepository.write(state);enhance();return state}
function syncSession(patch={}){const next={...session(),...patch};footmatePlatform.session.write(next);return next}
function navigate(route){syncSession({route});location.reload()}
function statusCopy(status){return {upcoming:['경기 준비','경기 시작 20분 전부터 체크인할 수 있어요.'],matchday:['도착 준비','경기장 도착 상태를 확인하고 체크인을 완료해주세요.'],'checked-in':['체크인 완료','도착 확인이 끝났습니다. 팀 공지와 경기장 안내를 확인하세요.'],late:['늦을 것 같아요','도착 지연 상태를 저장했습니다. 운영자에게 전달되는 UX 계약을 시뮬레이션합니다.'],updated:['운영 변경 확인','변경 공지를 확인했습니다. 최신 안내를 기준으로 이동해주세요.'],canceled:['경기 취소','운영 취소 상태입니다. 참가비 반환과 대체 경기 탐색 흐름을 확인할 수 있습니다.']}[status]||['경기 준비','경기 정보를 확인하세요.']}
function panel(){const [title,copy]=statusCopy(state.status);const primary=state.status==='upcoming'?'<button type="button" data-matchday-action="arrive">도착 상태 알리기</button>':state.status==='matchday'||state.status==='late'?'<button type="button" data-matchday-action="checkin">체크인 완료</button>':state.status==='canceled'?'<button type="button" data-matchday-action="find">다른 경기 찾기</button>':'<button type="button" data-matchday-action="notice">공지 다시 보기</button>';return `<section class="fm-matchday-panel" data-matchday-version="${MATCHDAY_VERSION}" data-matchday-state="${state.status}" aria-label="경기 당일 운영"><div class="fm-matchday-kicker">MATCHDAY · ${MATCHDAY_VERSION}</div><div class="fm-matchday-status" role="status"><b>${title}</b><span>${copy}</span></div><div class="fm-matchday-grid"><article><small>체크인</small><b>킥오프 20분 전부터</b><span>이 프로토타입은 시간창과 도착 상태 계약만 검증합니다.</span></article><article><small>경기장 안내</small><b>메인 출입구 → 3층 코트</b><span>주소·동선은 샘플 안내이며 실시간 지도 연동이 아닙니다.</span></article><article><small>팀 공지</small><b>조끼는 현장 제공</b><span>메시지 전송 backend 없이 공지 확인 UX만 시뮬레이션합니다.</span></article></div><div class="fm-matchday-actions">${primary}${state.status!=='canceled'&&state.status!=='checked-in'?'<button type="button" data-matchday-action="late">늦을 것 같아요</button>':''}${state.status==='late'?'<button type="button" data-matchday-action="recover">도착 상태 수정</button>':''}${state.status!=='canceled'?'<button type="button" data-matchday-action="update">경기 변경 공지 보기</button>':''}</div><p class="fm-matchday-boundary">실시간 위치·지도·팀 채팅·알림 backend는 연결하지 않았습니다. 상태와 복구 흐름을 검증하는 deterministic simulation입니다.</p></section>`}
function homeStrip(){const [title,copy]=statusCopy(state.status);return `<div class="fm-matchday-home" data-matchday-home data-matchday-state="${state.status}"><small>MATCHDAY OPERATIONS</small><b>${title}</b><span>${copy}</span><button type="button" data-matchday-action="profile">MY에서 내 경기 보기</button></div>`}
function enhanceMatchHub(container){if(!container||!currentMatchId())return;container.setAttribute('data-matchday-module-version',MATCHDAY_VERSION);const existing=container.querySelector('[data-matchday-version]');if(!existing)container.insertAdjacentHTML('beforeend',panel());else if(existing.dataset.matchdayState!==state.status)existing.outerHTML=panel()}
function enhance(){state=initial();enhanceMatchHub(root?.querySelector('[data-screen="profile"] [data-my-matches]'));enhanceMatchHub(root?.querySelector('[data-screen="schedule"] [data-my-matches]'));const home=root?.querySelector('[data-screen="home"]');if(home&&currentMatchId()){const existing=home.querySelector('[data-matchday-home]');if(!existing){const context=home.querySelector('.fm-next-context-card');if(context)context.insertAdjacentHTML('afterend',homeStrip())}else if(existing.dataset.matchdayState!==state.status)existing.outerHTML=homeStrip()}}
document.addEventListener('click',event=>{const target=event.target.closest('[data-matchday-action]');if(!target)return;event.preventDefault();const action=target.dataset.matchdayAction;if(action==='arrive'){persist({status:'matchday',arrival:'on-the-way'});return}if(action==='checkin'){persist({status:'checked-in',arrival:'arrived'});const id=currentMatchId();syncSession({checkedInMatchId:id,matchStage:'matchday'});enhance();return}if(action==='late'){persist({status:'late',arrival:'late'});return}if(action==='recover'){persist({status:'matchday',arrival:'on-the-way'});return}if(action==='update'){persist({status:'updated',noticeSeen:true});return}if(action==='notice'){persist({noticeSeen:true});return}if(action==='find'){navigate('discover');return}if(action==='profile'){navigate('profile');return}},true);
const observer=new MutationObserver(enhance);if(root)observer.observe(root,{childList:true,subtree:true});window.__FOOTMATE_MATCHDAY__={version:MATCHDAY_VERSION,storageKey:MATCHDAY_STORAGE_KEY,read:()=>initial(),setStatus:(status,patch={})=>allowed.has(status)?persist({status,...patch}):initial(),reset:()=>{matchdayRepository.clear();state=initial();enhance();return state}};enhance();
