import {MATCHES,createState} from './data.js';
import {footmatePlatform} from './platform/application/platform.js';

const PERSONALIZATION_VERSION='4.7.0';
const PERSONALIZATION_STORAGE_KEY=footmatePlatform.storageKeys.personalization;
const personalizationRepository=footmatePlatform.repositories.personalization;
const root=document.getElementById('footmate-next');
let explanationOpen=false;

function readSession(){return createState(footmatePlatform.session.read()||{})}
function defaults(){return {version:PERSONALIZATION_VERSION,profile:null,recentMatchIds:[],favorites:{areas:[],timeWindows:[],formats:[]}}}
function readMemory(){const raw=personalizationRepository.read({})||{};return {version:PERSONALIZATION_VERSION,profile:raw.profile&&typeof raw.profile==='object'?raw.profile:null,recentMatchIds:Array.isArray(raw.recentMatchIds)?raw.recentMatchIds.filter(id=>MATCHES.some(match=>match.id===id)).slice(0,5):[],favorites:{areas:Array.isArray(raw.favorites?.areas)?raw.favorites.areas:[],timeWindows:Array.isArray(raw.favorites?.timeWindows)?raw.favorites.timeWindows:[],formats:Array.isArray(raw.favorites?.formats)?raw.favorites.formats:[]}}}
function writeMemory(next){const value={...defaults(),...next,version:PERSONALIZATION_VERSION,favorites:{...defaults().favorites,...next.favorites}};personalizationRepository.write(value);return value}
function writeSession(patch){const next={...readSession(),...patch};footmatePlatform.session.write(next);return next}
function memorySignature(memory=readMemory()){const profile=memory.profile?`${memory.profile.region}|${memory.profile.position}|${memory.profile.level}`:'none';return encodeURIComponent([profile,memory.recentMatchIds.join(','),memory.favorites.areas.join(','),memory.favorites.timeWindows.join(','),memory.favorites.formats.join(',')].join('::'))}
function timeWindow(match){const found=String(match.shortDate||match.dateLabel||'').match(/(\d{1,2}):\d{2}/);const hour=Number(found?.[1]);if(!Number.isFinite(hour))return '20';if(hour<20)return '19';if(hour<21)return '20';return '21+'}
const timeLabels={'19':'19시대','20':'20시대','21+':'21시 이후'};
function baseRank(session=readSession()){return window.__FOOTMATE_RETURN__?.rank?.(session)||window.__FOOTMATE_RECOMMENDATION__?.rank?.(session)||[]}
function rank(preferences={}){const session=createState({...readSession(),...preferences});const memory=readMemory();return baseRank(session).map(item=>{const match=MATCHES.find(value=>value.id===item.id);let adjustment=0;const memoryReasons=[];if(match&&memory.profile?.region===match.region){adjustment+=4;memoryReasons.push('저장한 생활권과 일치')}if(match&&memory.favorites.areas.includes(match.region)){adjustment+=12;memoryReasons.push('자주 찾는 지역')}if(match&&memory.favorites.timeWindows.includes(timeWindow(match))){adjustment+=7;memoryReasons.push(`선호 시간대 · ${timeLabels[timeWindow(match)]}`)}if(match&&memory.favorites.formats.includes(match.format)){adjustment+=5;memoryReasons.push(`선호 포맷 · ${match.format}`)}const recentIndex=memory.recentMatchIds.indexOf(item.id);if(recentIndex>=0){adjustment+=Math.max(1,4-recentIndex);memoryReasons.push('최근 확인한 경기')}return {...item,personalizationAdjustment:adjustment,memoryReasons,score:Number(item.score||0)+adjustment}}).sort((a,b)=>b.score-a.score||b.personalizationAdjustment-a.personalizationAdjustment||a.id.localeCompare(b.id))}
function saveProfile(profile={}){const session=readSession();const memory=readMemory();return writeMemory({...memory,profile:{region:profile.region||session.region,position:profile.position||session.position,level:profile.level||session.level,savedAt:new Date().toISOString()}})}
function setFavorites(favorites={}){const memory=readMemory();const unique=value=>[...new Set(Array.isArray(value)?value:[])];return writeMemory({...memory,favorites:{areas:unique(favorites.areas??memory.favorites.areas),timeWindows:unique(favorites.timeWindows??memory.favorites.timeWindows),formats:unique(favorites.formats??memory.favorites.formats)}})}
function rememberMatch(id){if(!MATCHES.some(match=>match.id===id))return readMemory();const memory=readMemory();return writeMemory({...memory,recentMatchIds:[id,...memory.recentMatchIds.filter(value=>value!==id)].slice(0,5)})}
function toggleFavorite(kind,value){const memory=readMemory();const key={area:'areas',time:'timeWindows',format:'formats'}[kind];if(!key)return memory;const set=new Set(memory.favorites[key]);set.has(value)?set.delete(value):set.add(value);return setFavorites({[key]:[...set]})}
function quickReturnHtml(memory){if(!memory.profile)return '';return `<button type="button" class="fm-personalization-quick" data-personalization-action="apply-profile">저장된 설정으로 바로 추천 보기 <span aria-hidden="true">→</span></button>`}
function optionButtons(values,kind,selected,labeler=value=>value){return values.map(value=>`<button type="button" data-personalization-action="toggle" data-kind="${kind}" data-value="${value}" aria-pressed="${selected.includes(value)}">${labeler(value)}</button>`).join('')}
function profilePanel(){const memory=readMemory();const sig=memorySignature(memory);const regions=[...new Set(MATCHES.map(match=>match.region))];const formats=[...new Set(MATCHES.map(match=>match.format))];return `<section class="fm-personalization-panel" data-personalization-version="${PERSONALIZATION_VERSION}" data-memory-signature="${sig}" aria-label="개인화 설정"><div class="fm-personalization-kicker">PERSONALIZATION · ${PERSONALIZATION_VERSION}</div><div class="fm-personalization-head"><div><b>${memory.profile?'저장한 추천 프로필':'추천 프로필을 저장해보세요'}</b><span>${memory.profile?`${memory.profile.region} · ${memory.profile.position} · ${memory.profile.level}`:'현재 지역·포지션·레벨을 다음 방문의 시작점으로만 저장합니다.'}</span></div><button type="button" data-personalization-action="save-profile">현재 설정 저장</button></div><fieldset><legend>자주 찾는 지역</legend><div class="fm-personalization-options">${optionButtons(regions,'area',memory.favorites.areas)}</div></fieldset><fieldset><legend>선호 시간대</legend><div class="fm-personalization-options">${optionButtons(Object.keys(timeLabels),'time',memory.favorites.timeWindows,value=>timeLabels[value])}</div></fieldset><fieldset><legend>선호 경기 포맷</legend><div class="fm-personalization-options">${optionButtons(formats,'format',memory.favorites.formats)}</div></fieldset><div class="fm-personalization-actions"><button type="button" data-action="edit-setup">기본 설정 수정</button><button type="button" data-personalization-action="reset">개인화 기록 초기화</button></div><p class="fm-personalization-boundary">저장 프로필·최근 확인 경기·선호 지역/시간/포맷은 이 브라우저에만 남습니다. 회원 DB, 서버 메모리, 기기 간 동기화는 연결하지 않았습니다.</p></section>`}
function hasPersonalizationSignal(memory){return Boolean(memory.profile||memory.recentMatchIds.length||memory.favorites.areas.length||memory.favorites.timeWindows.length||memory.favorites.formats.length)}
function explanationHtml(){const memory=readMemory();if(!hasPersonalizationSignal(memory))return '';const top=rank()[0];const match=MATCHES.find(item=>item.id===top?.id);if(!top||!match||Number(top.personalizationAdjustment||0)<=0)return '';const baseReasons=(top.reasons||[]).slice(0,2);const details=[...baseReasons,...(top.memoryReasons||[])].slice(0,4);const sig=encodeURIComponent(`${memorySignature(memory)}|${top.id}|${top.score}|${explanationOpen}`);return `<section class="fm-personalization-explanation" data-personalization-explanation data-explanation-signature="${sig}"><div><small>추천 이유 개인화</small><b>${match.place}</b></div><button type="button" data-personalization-action="explain" aria-expanded="${explanationOpen}">왜 추천됐나요?</button>${explanationOpen?`<ul>${details.map(reason=>`<li>${reason}</li>`).join('')}</ul>`:''}</section>`}
function enhanceWelcome(){if(!root)return;const screen=root.querySelector('[data-screen="welcome"]');if(!screen)return;const actions=screen.querySelector('.fm-next-actions');if(!actions)return;const existing=actions.querySelector('.fm-personalization-quick');const html=quickReturnHtml(readMemory());if(html&&!existing)actions.insertAdjacentHTML('beforeend',html);if(!html&&existing)existing.remove()}
function enhanceProfile(){if(!root)return;const screen=root.querySelector('[data-screen="profile"]');if(!screen)return;const existing=screen.querySelector('.fm-personalization-panel');const sig=memorySignature();if(existing?.dataset.memorySignature===sig)return;const html=profilePanel();if(existing)existing.outerHTML=html;else{const card=screen.querySelector('.fm-next-profile-card');if(card)card.insertAdjacentHTML('afterend',html)}}
function enhanceExplanation(){if(!root)return;for(const screen of root.querySelectorAll('[data-screen="home"],[data-screen="discover"]')){const existing=screen.querySelector('[data-personalization-explanation]');const html=explanationHtml();if(!html){existing?.remove();continue}const probe=document.createElement('div');probe.innerHTML=html;const sig=probe.firstElementChild?.dataset.explanationSignature;if(existing?.dataset.explanationSignature===sig)continue;if(existing){existing.outerHTML=html;continue}const section=screen.querySelector('.fm-next-section');if(section){section.insertAdjacentHTML('afterbegin',html);continue}const list=screen.querySelector('.fm-next-list');if(list)list.insertAdjacentHTML('beforebegin',html)}}
function enhanceRanking(){if(!root)return;const memory=readMemory();const ranked=rank();const order=new Map(ranked.map((item,index)=>[item.id,{index,item}]));const scoreSig=ranked.map(item=>`${item.id}:${item.score}`).join(',');const sig=encodeURIComponent(`${memorySignature(memory)}|${scoreSig}`);for(const screen of root.querySelectorAll('[data-screen="home"],[data-screen="discover"]')){const list=screen.querySelector('.fm-next-list');if(!list||list.dataset.fmPersonalizationSignature===sig)continue;list.dataset.fmPersonalizationSignature=sig;const cards=[...list.querySelectorAll('.fm-next-match-card')];cards.sort((a,b)=>(order.get(a.dataset.matchId)?.index??999)-(order.get(b.dataset.matchId)?.index??999));cards.forEach(card=>{card.querySelectorAll('.fm-personalization-reason').forEach(node=>node.remove());const item=order.get(card.dataset.matchId)?.item;if(item?.personalizationAdjustment>0){const body=card.querySelector('.fm-next-match-body')||card;body.insertAdjacentHTML('afterbegin',`<span class="fm-personalization-reason">내 이용 기록 반영 +${item.personalizationAdjustment}</span>`)}list.appendChild(card)})}}
function refresh(){if(!root)return;enhanceWelcome();enhanceProfile();enhanceRanking();enhanceExplanation();root.dataset.personalizationVersion=PERSONALIZATION_VERSION}
function reset(){personalizationRepository.clear();explanationOpen=false;refresh();return readMemory()}

document.addEventListener('click',event=>{const open=event.target.closest('[data-action="open-match"]');if(open?.dataset.matchId){rememberMatch(open.dataset.matchId);return}const target=event.target.closest('[data-personalization-action]');if(!target)return;event.preventDefault();event.stopPropagation();const action=target.dataset.personalizationAction;if(action==='save-profile'){saveProfile();refresh();return}if(action==='toggle'){toggleFavorite(target.dataset.kind,target.dataset.value);refresh();return}if(action==='reset'){reset();return}if(action==='explain'){explanationOpen=!explanationOpen;enhanceExplanation();return}if(action==='apply-profile'){const profile=readMemory().profile;if(!profile)return;writeSession({...profile,setupComplete:true,route:'home'});location.reload()}},true);
const observer=new MutationObserver(()=>requestAnimationFrame(refresh));if(root)observer.observe(root,{childList:true,subtree:true});
window.__FOOTMATE_PERSONALIZATION__={version:PERSONALIZATION_VERSION,storageKey:PERSONALIZATION_STORAGE_KEY,read:readMemory,rank,saveProfile,setFavorites,rememberMatch,reset};
refresh();
