(function(){
'use strict';
if(window.__footmatePatch)return; window.__footmatePatch=true;
const Core=window.FootMateCore;
if(!Core){console.error('[FootMate] core patch missing');return;}
const STORE='footmateRuntimeStateV2';
const META={
 suwon:{team:'수원 FC UNITED',venue:'수원 풋살아레나 A코트',region:'수원시 영통구',regionKey:'suwon',timeKey:'morning',dateKey:'sat',time:'09:00',avgElo:1299,manner:4.2,distanceKm:1.2,formats:['5vs5'],positions:['MF','FW']},
 seongnam:{team:'성남 프리미어FC',venue:'성남 풋살파크',region:'성남시',regionKey:'seongnam',timeKey:'day',dateKey:'sun',time:'10:00',avgElo:1320,manner:4.8,distanceKm:0.8,formats:['5vs5','7vs7'],positions:['MF','DF']},
 yongin:{team:'용인 레전드팀',venue:'용인 풋살경기장',region:'용인시',regionKey:'seongnam',timeKey:'evening',dateKey:'sat',time:'15:00',avgElo:1278,manner:4.1,distanceKm:2.4,formats:['5vs5','7vs7'],positions:['FW','DF']}
};
Object.entries(META).forEach(([k,m])=>Object.assign(matchScenarioBases[k],m,{distance:m.distanceKm+'km'}));
const state=window.FootMateRuntime={answered:new Set(),participationMatchKey:null};
scenarioProfile.matchSkill=scenarioProfile.matchSkill??scenarioProfile.skill;
scenarioProfile.distanceKm=scenarioProfile.distanceKm??Number(document.getElementById('distanceRange')?.value||15);
scenarioProfile.format=scenarioProfile.format||'5vs5';
demoState.currentElo=Number.isFinite(Number(demoState.currentElo))?Number(demoState.currentElo):Number(demoState.initialElo);
demoState.eloBeforeUpdate=Number.isFinite(Number(demoState.eloBeforeUpdate))?Number(demoState.eloBeforeUpdate):Number(demoState.initialElo);
demoState.eloCommitted=Boolean(demoState.eloCommitted);

function ymd(d){return d instanceof Date?[d.getFullYear(),d.getMonth(),d.getDate()].join('-'):''}
function dateKey(){if(ymd(selectedDate)===ymd(SCENARIO_DATES.sat))return'sat';if(ymd(selectedDate)===ymd(SCENARIO_DATES.sun))return'sun';return ymd(selectedDate)||'sat'}
function meta(k=selectedMatchKey){return META[k]||META.suwon}
function fmt(m=meta()){return m.formats.includes(scenarioProfile.format)?scenarioProfile.format:m.formats[0]}
function tier(e){return e>=1450?'골드 I':e>=1375?'골드 II':e>=1300?'실버 III':e>=1225?'실버 II':e>=1150?'실버 I':'브론즈 III'}
function set(id,v){const el=document.getElementById(id);if(el)el.textContent=v;return el}
function save(){try{localStorage.setItem(STORE,JSON.stringify({currentElo:demoState.currentElo,eloBeforeUpdate:demoState.eloBeforeUpdate,updatedElo:demoState.updatedElo,eloCommitted:demoState.eloCommitted,result:demoState.postgameResult,selectedMatchKey,participationConfirmed,participationMatchKey:state.participationMatchKey,answered:[...state.answered],profile:{position:scenarioProfile.position,frequency:scenarioProfile.frequency,skill:scenarioProfile.skill,region:scenarioProfile.region,time:scenarioProfile.time,matchSkill:scenarioProfile.matchSkill,distanceKm:scenarioProfile.distanceKm,format:scenarioProfile.format,dateKey:dateKey()}}))}catch(e){}}
function restore(){let x;try{x=JSON.parse(localStorage.getItem(STORE)||'null')}catch(e){}if(!x)return;if(x.profile){['position','frequency','skill','region','time','matchSkill','distanceKm','format'].forEach(k=>{if(x.profile[k]!=null)scenarioProfile[k]=x.profile[k]});if(x.profile.dateKey==='sun')selectedDate=new Date(SCENARIO_DATES.sun);if(x.profile.dateKey==='sat')selectedDate=new Date(SCENARIO_DATES.sat)};if(Number.isFinite(+x.currentElo))demoState.currentElo=+x.currentElo;if(Number.isFinite(+x.eloBeforeUpdate))demoState.eloBeforeUpdate=+x.eloBeforeUpdate;if(Number.isFinite(+x.updatedElo))demoState.updatedElo=+x.updatedElo;demoState.eloCommitted=!!x.eloCommitted;if(x.result&&resultDisplay[x.result])demoState.postgameResult=x.result;if(META[x.selectedMatchKey])selectedMatchKey=x.selectedMatchKey;participationConfirmed=!!x.participationConfirmed;if(META[x.participationMatchKey])state.participationMatchKey=x.participationMatchKey;(x.answered||[]).forEach(k=>state.answered.add(k))}
restore();

[...document.querySelectorAll('#s-filter [data-skill-key]')].forEach(b=>{if(b.textContent.trim()==='중급')b.dataset.skillKey='1.5'});
document.querySelectorAll('#s-filter .filter-pill').forEach(b=>{const t=b.textContent.trim();if(t==='5vs5'||t==='7vs7')b.dataset.formatKey=t});

function baselineReplace(screenId,map){const root=document.getElementById(screenId);if(!root)return;const w=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);let n;while(n=w.nextNode()){if(n.__fmBase===undefined)n.__fmBase=n.nodeValue;let t=n.__fmBase;Object.entries(map).forEach(([a,b])=>t=t.split(a).join(b));n.nodeValue=t}}
function loadingValue(label){const root=document.getElementById('s-loading');if(!root)return null;for(const row of root.querySelectorAll('div')){const c=[...row.children];if(c.length>1&&c[0].textContent.trim()===label)return c[c.length-1]}return null}
function renderFilter(){scenarioProfile.dateKey=dateKey();const times={morning:'오전 (6~12시)',day:'낮 (12~17시)',evening:'저녁 (17~21시)',night:'야간 (21시 이후)'};const day=['일','월','화','수','목','금','토'][selectedDate.getDay()];const d=formatScenarioDate(selectedDate,day,'spaced');const r=regionDisplay[scenarioProfile.region]||scenarioProfile.regionLabel||'지역 미선택';const a=loadingValue('날짜'),b=loadingValue('위치'),c=loadingValue('실력');if(a)a.textContent=`${d} · ${times[scenarioProfile.time]||''}`;if(b)b.textContent=`${r} · ${scenarioProfile.distanceKm}km`;if(c)c.textContent=`${scenarioProfile.format} · ${Core.skillLabel(scenarioProfile.matchSkill)}`}
function renderFilterButtons(){document.querySelectorAll('#s-filter [data-time-key]').forEach(b=>{const a=b.dataset.timeKey===scenarioProfile.time;b.classList.toggle('active',a);b.setAttribute('aria-pressed',a)});document.querySelectorAll('#s-filter [data-skill-key]').forEach(b=>{const a=+b.dataset.skillKey===+scenarioProfile.matchSkill;b.classList.toggle('active',a);b.setAttribute('aria-pressed',a)});document.querySelectorAll('#s-filter [data-format-key]').forEach(b=>{const a=b.dataset.formatKey===scenarioProfile.format;b.classList.toggle('active',a);b.setAttribute('aria-pressed',a)});const r=document.getElementById('distanceRange');if(r)r.value=scenarioProfile.distanceKm;set('distanceVal',scenarioProfile.distanceKm)}
const oldToggle=togglePill;
togglePill=function(el){if(!el?.closest('#s-filter'))return oldToggle(el);const g=el.parentElement;g.querySelectorAll('.filter-pill').forEach(b=>{b.classList.remove('active');b.setAttribute('aria-pressed','false')});el.classList.add('active');el.setAttribute('aria-pressed','true');if(el.dataset.timeKey)scenarioProfile.time=el.dataset.timeKey;if(el.dataset.skillKey)scenarioProfile.matchSkill=+el.dataset.skillKey;if(el.dataset.formatKey)scenarioProfile.format=el.dataset.formatKey;renderFilter();recalculateMatches();save()};
updateDistance=function(v){scenarioProfile.distanceKm=Math.max(1,Math.min(30,+v||15));set('distanceVal',scenarioProfile.distanceKm);const r=document.getElementById('distanceRange');if(r){r.value=scenarioProfile.distanceKm;r.setAttribute('aria-valuenow',scenarioProfile.distanceKm);r.setAttribute('aria-valuetext',scenarioProfile.distanceKm+'km')}renderFilter();recalculateMatches();save()};
updateFilterSelections=renderFilterButtons;

calculateMatchScenario=function(key){const b=matchScenarioBases[key]||matchScenarioBases.suwon;const x=Core.scoreMatch(b,Object.assign({},scenarioProfile,{dateKey:dateKey()}),demoState,scoreWeights.balance);return Object.assign({},x,{positionFit:x.positions.includes(scenarioProfile.position),availablePosition:x.positions.includes(scenarioProfile.position)?scenarioProfile.position:x.positions[0],styleDesc:x.timeKey===scenarioProfile.time?'선호 시간대와 일치':'선호 시간대와 차이',locationDesc:x.eligibility.region&&x.eligibility.distance?`${x.distanceKm}km · 선택 지역/거리 내`:`${x.distanceKm}km · 선택 지역/거리 밖`})};
function cards(){const out={};document.querySelectorAll('#s-results [data-match-card]').forEach(c=>out[c.dataset.matchCard]=c);return out}
function emptyBox(){let e=document.getElementById('footmateRuntimeEmpty');if(e)return e;const pc=document.querySelector('#s-results .pcnt');if(!pc)return null;e=document.createElement('div');e.id='footmateRuntimeEmpty';e.innerHTML='<strong>선택한 조건에 맞는 경기가 없습니다.</strong>날짜·시간·지역·거리·경기 방식·모집 포지션을 조정해 보세요.<button class="btn-secondary" type="button" style="margin-top:10px">필터 다시 설정</button>';e.querySelector('button').onclick=()=>goScreen('s-filter');const first=pc.querySelector('[data-match-card]');first?pc.insertBefore(e,first):pc.prepend(e);return e}
function renderResults(){const ranked=Core.rankMatches(matchScenarioBases,Object.assign({},scenarioProfile,{dateKey:dateKey()}),demoState,scoreWeights.balance);const cs=cards();ranked.forEach((x,i)=>{const m=matchScenarios[x.key]=calculateMatchScenario(x.key),c=cs[x.key];if(!c)return;c.style.display=m.eligible?'':'none';c.setAttribute('aria-hidden',!m.eligible);set('result-pct-'+x.key,m.pct+'%');set('result-elo-diff-'+x.key,`ELO 차이 ${m.eloDiff} · ${m.positions.join('/')} 모집 · ${Core.skillLabel(scenarioProfile.matchSkill)}`);const bar=document.getElementById('result-skill-bar-'+x.key);if(bar)bar.style.width=m.eloScore+'%';const badge=document.getElementById('result-badge-'+x.key);if(badge){badge.textContent=i===0&&m.eligible?'🥇 Best Match':m.eligible?'조건 일치':'조건 불일치';badge.className='chip '+(i===0&&m.eligible?'chip-blue':m.eligible?'chip-green':'chip-gray')}const skill=c.querySelector('.result-chips .chip:first-child');if(skill){skill.textContent=m.eloDiff<=150?'실력 범위 ✓':`ELO 차이 ${m.eloDiff}`;skill.className='chip '+(m.eloDiff<=150?'chip-blue':'chip-orange')}const pos=x.key==='suwon'?document.getElementById('scenario-slot-chip'):c.querySelector('.result-chips .chip:last-child');if(pos)pos.textContent=m.positions.includes(scenarioProfile.position)?scenarioProfile.position+' 1자리':m.positions.join('/')+' 모집';c.onclick=()=>selectMatch(x.key,true)});const holder=Object.values(cs)[0]?.parentElement;if(holder){if(!window.__fmResultEnd){const all=[...holder.querySelectorAll('[data-match-card]')],mark=document.createComment('result-end');(all.at(-1)||holder.lastChild)?.after?.(mark);if(!mark.parentNode)holder.appendChild(mark);window.__fmResultEnd=mark}ranked.forEach(x=>cs[x.key]&&holder.insertBefore(cs[x.key],window.__fmResultEnd))}const ok=ranked.filter(x=>x.eligible);const banner=document.querySelector('#s-results .results-ai-banner');if(banner)banner.textContent=ok.length?`조건에 맞는 팀 ${ok.length}개 · 현재 ELO ${Core.effectiveElo(demoState).toLocaleString()} 기반 정렬`:'현재 조건에 맞는 경기가 없습니다.';const e=emptyBox();if(e)e.style.display=ok.length?'none':'';return ranked}
recalculateMatches=function(){Object.keys(matchScenarioBases).forEach(k=>matchScenarios[k]=calculateMatchScenario(k));renderResults();renderSelectedMatch();renderFilter()};

function renderIdentity(){const m=meta(),x=matchScenarios[selectedMatchKey]||calculateMatchScenario(selectedMatchKey),f=fmt(m),map={'수원 FC UNITED':m.team,'수원 풋살아레나 A코트':m.venue,'수원시 영통구':m.region,'평균 ELO 1299':'평균 ELO '+m.avgElo,'5vs5':f,'09:00':m.time,[SCENARIO_DATES.satCompact]:m.dateKey==='sun'?SCENARIO_DATES.sunCompact:SCENARIO_DATES.satCompact};['s-detail','s-pay','s-confirm','s-notifs','s-gameday','s-chat','s-venue','s-postgame','s-eval'].forEach(id=>baselineReplace(id,map));const title=document.querySelector('#s-detail .detail-team-name');if(title)title.textContent=m.team;set('detail-team-meta',`★ ${m.manner.toFixed(1)} · 매칭 ${x.pct}% · ${m.venue} · ${m.distanceKm}km`);set('detail-open-position',(x.availablePosition||m.positions[0])+' 1자리');set('ticket-position',x.positions.includes(scenarioProfile.position)?selectedPositionLabel():(x.availablePosition||m.positions[0]));}
renderSelectedMatch=function(){const x=matchScenarios[selectedMatchKey]||calculateMatchScenario(selectedMatchKey);if(!x)return;set('reasonMatchTitle',x.team);set('reasonMatchPct','왜 '+x.pct+'% 매칭인가요?');set('reasonEloScore',x.eloScore+'점');set('reasonStyleScore',x.styleScore+'점');set('reasonLocationScore',x.locationScore+'점');set('reasonEloDesc',`현재 ELO ${Core.effectiveElo(demoState).toLocaleString()} ↔ 팀 평균 ${x.avgElo.toLocaleString()} · 차이 ${x.eloDiff}`);set('reasonStyleDesc',x.styleDesc);set('reasonLocationDesc',x.locationDesc);renderIdentity()};
selectMatch=function(key,detail=false){selectedMatchKey=matchScenarios[key]?key:'suwon';renderSelectedMatch();save();goScreen(detail?'s-detail':'s-reason')};
document.querySelectorAll('#s-home [onclick*="s-detail"]').forEach(c=>{const t=c.textContent;const k=t.includes('성남 프리미어FC')?'seongnam':t.includes('용인 레전드팀')?'yongin':t.includes('수원 FC UNITED')?'suwon':null;if(k)c.onclick=()=>selectMatch(k,true)});

const oldV2=renderV2Comparison;
renderV2Comparison=function(){oldV2();const r=Core.rankMatches(matchScenarioBases,Object.assign({},scenarioProfile,{dateKey:dateKey()}),demoState,scoreWeights.balance),p=r.find(x=>x.eligible)||r[0];if(p){set('v2PrimaryTeam',p.team);set('v2PrimaryScore',p.pct+'%');set('v2MetricSkill',p.eloScore);set('v2MetricStyle',p.styleScore);set('v2MetricDistance',p.locationScore)}};
const oldAccept=acceptV2Replacement;
acceptV2Replacement=function(){selectedMatchKey='seongnam';renderSelectedMatch();oldAccept();const b=document.getElementById('v2OfferPayment');if(b)b.onclick=()=>{selectedMatchKey='seongnam';renderSelectedMatch();goScreen('s-pay')};save()};

function updateProfile(){const e=Core.effectiveElo(demoState),p=document.getElementById('s-profile');set('profile-elo-number',e.toLocaleString());if(p){const sub=p.querySelector('.profile-sub'),te=p.querySelector('.pec-tier');if(sub)sub.textContent=`${tier(e)} · ${regionDisplay[scenarioProfile.region]||scenarioProfile.regionLabel}`;if(te)te.textContent='🏅 '+tier(e)}}
calculateEloUpdate=function(){const base=demoState.eloCommitted?+demoState.eloBeforeUpdate:Core.effectiveElo(demoState),opp=meta(state.participationMatchKey||selectedMatchKey).avgElo,expected=1/(1+Math.pow(10,(opp-base)/400)),actual=demoState.postgameResult==='WIN'?1:demoState.postgameResult==='DRAW' ? .5 : 0,delta=Math.round(32*(actual-expected)),updated=base+delta;Object.assign(demoState,{expectedScore:expected,eloDelta:delta,updatedElo:updated});return{baseElo:base,opponentElo:opp,expectedScore:expected,actualScore:actual,delta,updatedElo:updated}};
function commitElo(){if(demoState.eloCommitted)return calculateEloUpdate();const u=calculateEloUpdate();demoState.eloBeforeUpdate=u.baseElo;demoState.currentElo=u.updatedElo;demoState.updatedElo=u.updatedElo;demoState.eloCommitted=true;recalculateMatches();updateProfile();save();return u}
const oldEloRender=renderEloUpdate;
renderEloUpdate=function(){oldEloRender();const u=calculateEloUpdate();set('eloOldNum',u.baseElo.toLocaleString());set('eloNewNum',u.updatedElo.toLocaleString());set('growth-elo-before',u.baseElo.toLocaleString());set('growth-elo-after',u.updatedElo.toLocaleString());updateProfile()};
submitEvaluation=function(){const s=document.getElementById('evalValidation');if(!selectedEvalStars){if(s)s.textContent='매너 점수를 먼저 선택해 주세요.';return}demoState.selectedRating=selectedEvalStars;commitElo();if(s)s.textContent=selectedEvalStars+'점 평가가 반영되었습니다.';goScreen('s-eloUpdate')};

recordParticipation=function(){participationConfirmed=true;state.participationMatchKey=selectedMatchKey;syncParticipationState();trackDemoEvent('payment_complete',{match:selectedMatchKey});renderIdentity();save()};
confirmParticipation=function(){recordParticipation();goScreen('s-confirm')};
syncParticipationState=function(){if(participationConfirmed&&state.participationMatchKey){const k=state.participationMatchKey,m=meta(k);const h=document.getElementById('s-home');if(h)baselineReplace('s-home',{'수원 FC UNITED':m.team,'수원 풋살아레나 A코트':m.venue,[SCENARIO_DATES.satCompact]:m.dateKey==='sun'?SCENARIO_DATES.sunCompact:SCENARIO_DATES.satCompact});set('home-upcoming-title','참가 예정 경기')}};
openUpcomingMatch=function(){if(participationConfirmed&&state.participationMatchKey)selectedMatchKey=state.participationMatchKey;renderSelectedMatch();goScreen(participationConfirmed?'s-gameday':'s-detail')};

const oldGo=goScreen;
goScreen=function(id){const k=selectedMatchKey;oldGo(id);if(['s-detail','s-pay','s-confirm','s-gameday','s-chat'].includes(id)&&META[k]){selectedMatchKey=k;renderSelectedMatch()}if(id==='s-filter')renderFilterButtons();if(id==='s-loading')renderFilter();if(id==='s-results')renderResults();if(id==='s-profile')updateProfile();if(id==='s-eloUpdate')renderEloUpdate();if(id==='s-v2-compare')renderV2Comparison();save()};
syncDemoHash=function(screenId){if(!demoStarted)return;const hash=hashByScreen[screenId]||screenId.replace(/^s-/,'');const target='#'+hash;try{const w=window.parent!==window&&window.parent.location.origin===location.origin?window.parent:window;if(w.location.hash!==target)w.history.replaceState(null,'',target)}catch(e){if(location.hash!==target)history.replaceState(null,'',target)}};

const oldQuiz=selectQuizOpt;
selectQuizOpt=function(el,i){const k=quizData[quizStep]?.key;if(k)state.answered.add(k);const r=oldQuiz(el,i);setTimeout(()=>{renderDataQuality();save()},0);return r};
renderDataQuality=function(){const grid=document.getElementById('v3DataQuality');if(!grid)return;const valid=Core.effectiveElo(demoState)>=900&&Core.effectiveElo(demoState)<=1800&&!!resultDisplay[demoState.postgameResult],consistent=!participationConfirmed||!!state.participationMatchKey,q=Core.dataQualityStatus({answeredCount:state.answered.size,eventCount:demoEvents.length,valid,consistent}),rows=[['Completeness',state.answered.size>=5?'5개 입력 확인':`${state.answered.size}/5 입력 확인`,q.completeness],['Validity',valid?'현재 ELO·결과 허용 범위':'허용 범위 확인 필요',q.validity],['Freshness','경기 정원·상태는 샘플 데이터',q.freshness],['Consistency',consistent?'선택 경기→결제→참가 상태 일치':'참가 경기 상태 확인 필요',q.consistency],['Traceability',`${Math.min(demoEvents.length,5)}/5 핵심 이벤트 기록`,q.traceability]];grid.innerHTML=rows.map(([n,d,b])=>`<div class="dq-row"><b>${n}</b><span>${d}</span><em class="dq-badge ${b.toLowerCase()}">${b}</em></div>`).join('')};
const oldTrack=trackDemoEvent;
trackDemoEvent=function(name,metadata={}){const e=demoEvents.find(x=>x.name===name);if(e){e.metadata=Object.assign({},e.metadata||{},metadata);renderDataQuality();save();return e}const r=oldTrack(name,metadata);renderDataQuality();save();return r};
const oldReplay=replayFootMateDemo;
replayFootMateDemo=function(){try{localStorage.removeItem(STORE)}catch(e){}return oldReplay()};

syncDynamicScenario=function(){if(!demoState.eloCommitted){demoState.initialElo=calculateInitialElo();demoState.currentElo=demoState.initialElo;demoState.eloBeforeUpdate=demoState.initialElo}scenarioProfile.matchSkill=scenarioProfile.matchSkill??scenarioProfile.skill;recalculateMatches();calculateEloUpdate();renderEloUpdate();renderFilterButtons();renderFilter();renderDataQuality();syncParticipationState();updateProfile();save()};
syncScenarioPosition=function(){const x=matchScenarios[selectedMatchKey]||calculateMatchScenario(selectedMatchKey),p=x.positions.includes(scenarioProfile.position)?scenarioProfile.position:x.positions[0];const d=document.getElementById('detail-open-position');if(d)d.childNodes.length?d.childNodes[0].nodeValue=p:d.textContent=p;set('ticket-position',x.positions.includes(scenarioProfile.position)?selectedPositionLabel():p)};

renderFilterButtons();renderFilter();recalculateMatches();updateProfile();syncParticipationState();renderDataQuality();renderSelectedMatch();
console.info('[FootMate] consistency patch 2026-09-09.1 applied',{elo:Core.effectiveElo(demoState),selectedMatchKey});
})();
