const {test,expect}=require('@playwright/test');
const AxeBuilder=require('@axe-core/playwright').default;
function failures(page){const items=[];page.on('pageerror',error=>items.push(`pageerror: ${error.message}`));page.on('console',message=>{if(message.type()==='error'&&!message.text().includes('Failed to load resource'))items.push(`console.error: ${message.text()}`)});return items}
async function ready(page){await page.waitForFunction(()=>window.__FOOTMATE_REAL_APP_FLOW__?.version==='1.3.0')}
async function openClean(page){await page.setViewportSize({width:390,height:844});await page.goto('/app',{waitUntil:'domcontentloaded'});await page.evaluate(()=>{localStorage.clear();sessionStorage.clear()});await page.reload({waitUntil:'domcontentloaded'});await ready(page)}
async function chooseSetup(page){await page.getByRole('button',{name:/내 경기 찾아보기/}).click();await page.locator('[data-action="choose-setup"][data-value="수원 · 영통"]').click();await page.getByRole('button',{name:'다음'}).click();await page.locator('[data-action="choose-setup"][data-value="MF"]').click();await page.getByRole('button',{name:'다음'}).click();await page.locator('[data-action="choose-setup"][data-value="중급"]').click();await page.getByRole('button',{name:/추천 경기 보기/}).click();await expect(page.locator('[data-screen="home"]')).toBeVisible()}
async function openDirect(page,route,extra={}){await page.setViewportSize({width:390,height:844});await page.goto('/app',{waitUntil:'domcontentloaded'});await page.evaluate(({route,extra})=>{localStorage.clear();localStorage.setItem('footmate:v4:session',JSON.stringify({route,setupComplete:true,setupStep:0,region:'수원 · 영통',position:'MF',level:'중급',signedIn:false,joinedMatchId:null,selectedMatchId:'suwon-ingye-2000',matchStage:'discover',userName:'게스트',...extra}))},{route,extra});await page.reload({waitUntil:'domcontentloaded'});await ready(page);await expect(page.locator(`[data-screen="${route}"]`)).toBeVisible()}

test('fresh setup gets a first-use completion greeting and detail back keeps its origin',async({page})=>{const errs=failures(page);await openClean(page);await chooseSetup(page);const home=page.locator('[data-screen="home"]');await expect(home.locator('[data-flow-first-home-copy]')).toContainText('설정이 완료됐어요');await expect(home.locator('[data-flow-first-home-copy]')).toContainText('조건에 맞는 경기를 찾았어요.');await home.locator('.fm-next-match-card').first().click();await expect(page.locator('[data-screen="detail"]')).toBeVisible();await page.getByRole('button',{name:'이전 화면'}).click();await expect(page.locator('[data-screen="home"]')).toBeVisible();await page.getByRole('button',{name:'경기 찾기',exact:true}).click();const discover=page.locator('[data-screen="discover"]');await discover.locator('.fm-next-match-card').first().click();await page.getByRole('button',{name:'이전 화면'}).click();await expect(page.locator('[data-screen="discover"]')).toBeVisible();expect(errs).toEqual([])});

test('account login adds loading failure and retry without changing validation ownership',async({page})=>{const errs=failures(page);await openDirect(page,'detail');await page.getByRole('button',{name:'참가하기'}).click();await expect(page.locator('[data-screen="auth"]')).toBeVisible();await ready(page);await page.getByRole('textbox',{name:'아이디'}).fill('member01');await page.getByLabel('비밀번호',{exact:true}).fill('password123!');await page.evaluate(()=>window.__FOOTMATE_REAL_APP_FLOW__.setNextAuthOutcome('failure'));const login=page.getByRole('button',{name:'로그인',exact:true});await login.click();await expect(page.locator('[data-flow-auth-status]')).toContainText('확인하고 있어요');await expect(page.locator('[data-flow-auth-status]')).toContainText('다시 시도해주세요');await login.click();await expect(page.locator('[data-screen="checkout"]')).toBeVisible();await expect(page.locator('[data-p1-checkout-boundary]')).toHaveText('체험 결제 · 실제 청구 없음');expect(errs).toEqual([])});

test('saved matches have a MY destination and technical disclosure opens only on demand',async({page})=>{const errs=failures(page);await openDirect(page,'detail');await page.getByRole('button',{name:'저장',exact:true}).click();await page.evaluate(()=>{const session=JSON.parse(localStorage.getItem('footmate:v4:session')||'{}');localStorage.setItem('footmate:v4:session',JSON.stringify({...session,route:'profile'}))});await page.reload({waitUntil:'domcontentloaded'});await ready(page);const profile=page.locator('[data-screen="profile"]');const saved=profile.locator('[data-flow-saved]');await expect(saved).toContainText('수원 인계 풋살파크');await saved.getByRole('button',{name:/수원 인계 풋살파크/}).click();await page.getByRole('button',{name:'이전 화면'}).click();await expect(profile).toBeVisible();const info=profile.locator('[data-action="reset-flow"]');await expect(info).toHaveAttribute('aria-label','체험 버전 안내');await info.click();const dialog=page.getByRole('dialog',{name:'체험 버전 안내'});await expect(dialog).toContainText('실제 계정이나 금액과 연결되지 않습니다');const result=await new AxeBuilder({page}).include('.fm-flow-info-dialog').withTags(['wcag2a','wcag2aa']).analyze();expect(result.violations.filter(item=>['serious','critical'].includes(item.impact))).toEqual([]);await dialog.getByRole('button',{name:'닫기'}).click();expect(errs).toEqual([])});

test('decision matchday and postgame surfaces expose user-facing labels without changing stored contracts',async({page})=>{const errs=failures(page);await openDirect(page,'detail');const detail=page.locator('[data-screen="detail"]');await expect(detail.locator('.fm-decision-capacity small')).toHaveText('남은 자리');await expect(detail.locator('.fm-next-detail-meta > span:first-child').first()).not.toContainText('샘플 일정');await page.evaluate(()=>{const session=JSON.parse(localStorage.getItem('footmate:v4:session')||'{}');localStorage.setItem('footmate:v4:session',JSON.stringify({...session,route:'profile',signedIn:true,joinedMatchId:'suwon-ingye-2000',matchStage:'upcoming',userName:'도현'}));localStorage.setItem('footmate:v4:matchday',JSON.stringify({matchId:'suwon-ingye-2000',status:'upcoming',startsAt:new Date(Date.now()+10*60000).toISOString()}))});await page.reload({waitUntil:'domcontentloaded'});await ready(page);const profile=page.locator('[data-screen="profile"]');await expect(profile.locator('.fm-matchday-kicker')).toHaveText('오늘 경기');await expect(profile.locator('.fm-matchday-boundary')).toContainText('외부 서비스는 연결하지 않았습니다');await page.evaluate(()=>{const session=JSON.parse(localStorage.getItem('footmate:v4:session')||'{}');localStorage.setItem('footmate:v4:session',JSON.stringify({...session,route:'schedule',matchStage:'postgame'}))});await page.reload({waitUntil:'domcontentloaded'});await ready(page);await expect(page.locator('.fm-return-kicker')).toHaveText('경기 후 피드백');await expect(page.locator('.fm-return-boundary').first()).toContainText('다음 경기 추천');expect(errs).toEqual([])});
