const {test,expect}=require('@playwright/test');
const AxeBuilder=require('@axe-core/playwright').default;
function failures(page){const items=[];page.on('pageerror',e=>items.push(`pageerror: ${e.message}`));page.on('console',m=>{if(m.type()==='error'&&!m.text().includes('Failed to load resource'))items.push(`console.error: ${m.text()}`)});return items}
async function boot(page,path='/app',viewport={width:390,height:844}){const errs=failures(page);await page.setViewportSize(viewport);await page.goto(path,{waitUntil:'domcontentloaded'});await page.waitForSelector('#footmate-next [data-screen]');return errs}
async function setup(page){await page.getByRole('button',{name:/내 경기 찾아보기/}).click();await page.getByRole('button',{name:'다음'}).click();await page.getByRole('button',{name:'다음'}).click();await page.getByRole('button',{name:/추천 경기 보기/}).click();await expect(page.locator('[data-screen="home"]')).toBeVisible()}
async function configure(page,{region,position,level}){await page.getByRole('button',{name:/내 경기 찾아보기/}).click();if(region)await page.locator(`[data-action="choose-setup"][data-field="region"][data-value="${region}"]`).click();await page.getByRole('button',{name:'다음'}).click();if(position)await page.locator(`[data-action="choose-setup"][data-field="position"][data-value="${position}"]`).click();await page.getByRole('button',{name:'다음'}).click();if(level)await page.locator(`[data-action="choose-setup"][data-field="level"][data-value="${level}"]`).click();await page.getByRole('button',{name:/추천 경기 보기/}).click();await expect(page.locator('[data-screen="home"]')).toBeVisible();await expect(page.locator('.fm-next-match-card').first()).toHaveAttribute('data-recommendation-score',/\d+/)}
async function auth(page){await setup(page);await page.locator('.fm-next-match-card').first().click();await page.getByRole('button',{name:'참가하기'}).click();await expect(page.locator('[data-screen="auth"]')).toBeVisible()}
test.beforeEach(async({page})=>{await page.goto('/app',{waitUntil:'domcontentloaded'});await page.evaluate(()=>localStorage.clear())});

test('v4.4 official release remains guest-first and hides portfolio identity',async({page})=>{const errs=await boot(page);await expect(page.locator('meta[name="footmate-release"]')).toHaveAttribute('content','4.4.0');await expect(page.getByText('둘러보는 데 계정이 필요하지 않아요.')).toBeVisible();await setup(page);await expect(page.locator('.fm-next-match-card')).toHaveCount(2);await expect(page.locator('.fm-next-greeting')).not.toContainText('도현');await page.getByRole('button',{name:'내 정보'}).click();await expect(page.locator('.fm-next-profile-head')).toContainText('게스트');expect(errs).toEqual([])});

test('v4.4 preserves preference-aware recommendation order and explanation',async({page})=>{const errs=await boot(page);await configure(page,{region:'서울 · 강남',position:'GK',level:'입문'});const first=page.locator('.fm-next-match-card').first();await expect(first).toHaveAttribute('data-match-id','songpa-2100');await expect(first).toContainText('잠실 리턴 풋살파크');await expect(first).toContainText('GK 1자리');await first.click();await expect(page.locator('[data-screen="detail"]')).toHaveAttribute('data-recommendation-score',/\d+/);await expect(page.locator('.fm-next-detail-section').first()).toContainText('선호 생활권과 일치');await expect(page.locator('.fm-next-detail-section').first()).toContainText('체감 레벨이 정확히 맞아요');await expect(page.locator('.fm-next-detail-section').first()).toContainText('GK 1자리 남음');expect(errs).toEqual([])});

test('v4.4 preserves a different preference profile producing a different top match',async({page})=>{const errs=await boot(page);await configure(page,{region:'용인 · 기흥',position:'FW',level:'중급+'});await expect(page.locator('.fm-next-match-card').first()).toHaveAttribute('data-match-id','jukjeon-2100');await expect(page.locator('.fm-next-match-card').first()).toContainText('죽전 플레이돔');await expect(page.locator('.fm-next-match-card').first()).toContainText('FW 2자리');expect(errs).toEqual([])});

test('v4 validates account input and preserves selected match through checkout',async({page})=>{const errs=await boot(page);await auth(page);const login=page.getByRole('button',{name:'로그인'});await login.click();await expect(page.locator('.fm-auth-error')).toHaveCount(2);await page.getByRole('textbox',{name:'아이디 또는 이메일'}).fill('member@example.com');await page.getByLabel('비밀번호',{exact:true}).fill('password123!');await login.click();await expect(page.locator('[data-screen="checkout"]')).toBeVisible();await page.getByRole('button',{name:/결제하고 참가 확정/}).click();await expect(page.locator('[data-screen="success"]')).toBeVisible();expect(errs).toEqual([])});

test('v4 detail back returns to entry surface',async({page})=>{const errs=await boot(page);await setup(page);await page.locator('.fm-next-match-card').first().click();await page.getByRole('button',{name:'이전 화면'}).click();await expect(page.locator('[data-screen="home"]')).toBeVisible();await page.getByRole('button',{name:'전체 보기'}).click();await page.locator('.fm-next-match-card').first().click();await page.getByRole('button',{name:'이전 화면'}).click();await expect(page.locator('[data-screen="discover"]')).toBeVisible();expect(errs).toEqual([])});

test('v4 matchday check-in persists across reload',async({page})=>{const errs=await boot(page,'/app?mode=evidence',{width:1280,height:900});await page.getByRole('button',{name:'경기 당일'}).click();await page.getByRole('button',{name:'체크인하기'}).click();await expect(page.getByRole('button',{name:'체크인 완료'})).toBeDisabled();await page.reload({waitUntil:'domcontentloaded'});await page.getByRole('button',{name:'경기 당일'}).click();await expect(page.getByRole('button',{name:'체크인 완료'})).toBeDisabled();expect(errs).toEqual([])});

test('v4 real/guided/evidence modes remain isolated',async({page})=>{let errs=await boot(page);await setup(page);await expect(page.locator('.fm-next-guide')).toHaveCount(0);await expect(page.getByText('EVIDENCE MODE',{exact:true})).toHaveCount(0);expect(errs).toEqual([]);errs=failures(page);await page.setViewportSize({width:1280,height:900});await page.goto('/app?mode=guided',{waitUntil:'domcontentloaded'});await expect(page.getByText('Guided Case Study')).toBeVisible();await page.goto('/app?mode=evidence',{waitUntil:'domcontentloaded'});await expect(page.getByText('EVIDENCE MODE',{exact:true})).toBeVisible();expect(errs).toEqual([])});

test('v4 remains responsive and accessible at supported mobile widths',async({page})=>{for(const width of [320,375,390,430]){const errs=await boot(page,'/app',{width,height:780});expect(await page.evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth)).toBeLessThanOrEqual(1);await setup(page);const heights=await page.locator('.fm-next-nav button').evaluateAll(nodes=>nodes.map(n=>n.getBoundingClientRect().height));heights.forEach(h=>expect(h).toBeGreaterThanOrEqual(44));expect(errs).toEqual([]);await page.evaluate(()=>localStorage.clear())}const errs=await boot(page);await setup(page);const result=await new AxeBuilder({page}).include('.fm-next-app').withTags(['wcag2a','wcag2aa']).analyze();expect(result.violations.filter(v=>['serious','critical'].includes(v.impact))).toEqual([]);expect(errs).toEqual([])});

test('v4.4 Case Study is official, product-first and mobile-safe',async({page})=>{const errs=failures(page);await page.setViewportSize({width:1440,height:900});await page.goto('/',{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>document.querySelectorAll('.slide').length===16&&document.documentElement.dataset.footmateCaseStudyRelease==='4.4.0');await expect(page.locator('.slide')).toHaveCount(16);await expect(page.locator('.fm-next-cover-note')).toContainText('v4.4.0');await expect(page.locator('.fm-next-cover-frame iframe')).toHaveAttribute('src','/app?embed=1');await page.evaluate(()=>window.goTo(7));await expect(page.locator('.slide.on')).toContainText('저장 · 최대 2경기 비교 · 참가하기');await page.evaluate(()=>window.goTo(9));await expect(page.locator('.slide.on')).toContainText('checkout → pending → success | failure | canceled');expect((await page.locator('body').innerText()).toLowerCase()).not.toContain('next major candidate');await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth)).toBeLessThanOrEqual(1);expect(errs).toEqual([])});

test('legacy public routes resolve to the v4.4 surface',async({page})=>{for(const route of ['/demo','/next']){await page.goto(route,{waitUntil:'domcontentloaded'});await expect(page.locator('meta[name="footmate-release"]')).toHaveAttribute('content','4.4.0');await expect(page.getByRole('heading',{name:/내 수준에 맞는 경기부터/})).toBeVisible()}});

test('v4.4 guided mode returns to the official /app surface',async({page})=>{const errs=await boot(page,'/app?mode=guided',{width:1280,height:900});await expect(page.getByText('v4 공식 경험입니다.',{exact:false})).toBeVisible();await expect(page.getByText('다음 버전 경험입니다.',{exact:false})).toHaveCount(0);await page.getByRole('button',{name:'Real App만 보기'}).click();await expect(page).toHaveURL(/\/app$/);await expect(page.locator('meta[name="footmate-release"]')).toHaveAttribute('content','4.4.0');expect(errs).toEqual([])});

test('v4.4 sample schedules stay relative instead of aging into past dates',async({page})=>{const errs=await boot(page);await setup(page);const labels=await page.locator('.fm-next-match-date > span:first-child').allTextContents();const expected=await page.evaluate(()=>{const values=[];for(let offset=1;offset<=4;offset+=1){const d=new Date();d.setHours(12,0,0,0);d.setDate(d.getDate()+offset);values.push(new Intl.DateTimeFormat('ko-KR',{month:'long',day:'numeric'}).format(d))}return values});expect(labels.length).toBeGreaterThan(0);for(const label of labels){expect(label).toContain('샘플 일정');expect(expected.some(day=>label.includes(day))).toBe(true)}expect(errs).toEqual([])});

test('v4.4 check-in persistence is isolated to the joined match',async({page})=>{const errs=await boot(page);await page.evaluate(()=>{localStorage.setItem('footmate:v4:session',JSON.stringify({setupComplete:true,route:'schedule',signedIn:true,joinedMatchId:'gwanggyo-2130',selectedMatchId:'gwanggyo-2130',matchStage:'matchday'}));localStorage.setItem('footmate:v4:interaction',JSON.stringify({checkedInMatchId:'suwon-ingye-2000',checkedInAt:Date.now()}));location.reload()});await page.waitForSelector('[data-screen="schedule"]');await expect(page.getByRole('button',{name:'체크인'})).toBeVisible();await expect(page.getByRole('button',{name:'체크인 완료'})).toHaveCount(0);await page.getByRole('button',{name:'체크인'}).click();await expect(page.getByRole('button',{name:'체크인 완료'})).toBeDisabled();expect(errs).toEqual([])});

test('v4.4 route transitions move programmatic focus to the active screen',async({page})=>{const errs=await boot(page);await expect(page.locator('[data-screen="welcome"]')).toHaveAttribute('tabindex','-1');expect(await page.evaluate(()=>document.activeElement?.dataset?.screen)).toBe('welcome');await page.getByRole('button',{name:/내 경기 찾아보기/}).click();expect(await page.evaluate(()=>document.activeElement?.dataset?.screen)).toBe('setup');await page.getByRole('button',{name:'다음'}).click();await page.getByRole('button',{name:'다음'}).click();await page.getByRole('button',{name:/추천 경기 보기/}).click();await page.locator('.fm-next-match-card').first().click();expect(await page.evaluate(()=>document.activeElement?.dataset?.screen)).toBe('detail');expect(errs).toEqual([])});
