const {test,expect}=require('@playwright/test');

async function openClean(page){await page.goto('/app',{waitUntil:'domcontentloaded'});await page.evaluate(()=>localStorage.clear())}
async function setup(page){await page.getByRole('button',{name:/내 경기 찾아보기/}).click();await page.getByRole('button',{name:'다음'}).click();await page.getByRole('button',{name:'다음'}).click();await page.getByRole('button',{name:/추천 경기 보기/}).click();await expect(page.locator('[data-screen="home"]')).toBeVisible()}

test.beforeEach(async({page})=>{await openClean(page)});

test('legacy session migrates to schema v2 before the real app restores it',async({page})=>{await page.evaluate(()=>localStorage.setItem('footmate:v4:session',JSON.stringify({route:'home',setupComplete:true,region:'수원 · 영통',position:'MF',level:'중급',signedIn:false,selectedMatchId:'gwanggyo-2130',joinedMatchId:null,matchStage:'discover',userName:'레거시',legacyFlag:'preserved'})));await page.reload({waitUntil:'domcontentloaded'});await expect(page.locator('[data-screen="home"]')).toBeVisible();await expect(page.locator('#footmate-next')).toHaveAttribute('data-session-schema-version','2');const state=await page.evaluate(()=>JSON.parse(localStorage.getItem('footmate:v4:session')||'{}'));expect(state.schemaVersion).toBe(2);expect(state.route).toBe('home');expect(state.legacyFlag).toBe('preserved');const contract=await page.evaluate(()=>({version:window.__FOOTMATE_PLATFORM__?.version,provider:window.__FOOTMATE_PLATFORM__?.provider,externalAnalytics:window.__FOOTMATE_PLATFORM__?.externalAnalytics}));expect(contract).toEqual({version:'4.8.0',provider:'local-browser',externalAnalytics:false})});

test('recommendation selection writes the platform event contract',async({page})=>{await page.reload({waitUntil:'domcontentloaded'});await setup(page);const card=page.locator('.fm-next-match-card').first();const matchId=await card.getAttribute('data-match-id');await card.click();const events=await page.evaluate(()=>window.__FOOTMATE_PLATFORM__.readEvents());const selected=events.find(event=>event.name==='recommendation.selected');expect(selected?.schemaVersion).toBe(1);expect(selected?.payload.matchId).toBe(matchId);expect(selected?.id).toMatch(/^evt-\d{4}$/)});

test('join completion event is reload-idempotent for one payment attempt',async({page})=>{await page.evaluate(()=>{localStorage.setItem('footmate:v4:session',JSON.stringify({route:'success',setupComplete:true,region:'수원 · 영통',position:'MF',level:'중급',signedIn:true,selectedMatchId:'gwanggyo-2130',joinedMatchId:'gwanggyo-2130',matchStage:'upcoming',userName:'테스터'}));localStorage.setItem('footmate:v4:participation',JSON.stringify({schemaVersion:1,version:'4.4.0',status:'success',matchId:'gwanggyo-2130',amount:13000,paymentMethod:'easy',attemptId:'pay-contract-1',attemptNumber:1,confirmationId:'FM-CONTRACT'}))});await page.reload({waitUntil:'domcontentloaded'});await page.waitForSelector('#footmate-next [data-screen]');let events=await page.evaluate(()=>window.__FOOTMATE_PLATFORM__.readEvents());expect(events.filter(event=>event.name==='join.completed')).toHaveLength(1);await page.reload({waitUntil:'domcontentloaded'});await page.waitForSelector('#footmate-next [data-screen]');events=await page.evaluate(()=>window.__FOOTMATE_PLATFORM__.readEvents());expect(events.filter(event=>event.name==='join.completed')).toHaveLength(1)});
