const {test,expect}=require('@playwright/test');
const AxeBuilder=require('@axe-core/playwright').default;
function failures(page){const items=[];page.on('pageerror',e=>items.push(`pageerror: ${e.message}`));page.on('console',m=>{if(m.type()==='error'&&!m.text().includes('Failed to load resource'))items.push(`console.error: ${m.text()}`)});return items}
async function boot(page,path='/app',viewport={width:390,height:844}){const errs=failures(page);await page.setViewportSize(viewport);await page.goto(path,{waitUntil:'domcontentloaded'});await page.waitForSelector('#footmate-next [data-screen]');return errs}
async function setup(page){await page.getByRole('button',{name:/내 경기 찾아보기/}).click();await page.getByRole('button',{name:'다음'}).click();await page.getByRole('button',{name:'다음'}).click();await page.getByRole('button',{name:/추천 경기 보기/}).click();await expect(page.locator('[data-screen="home"]')).toBeVisible()}
test.beforeEach(async({page})=>{await page.goto('/app',{waitUntil:'domcontentloaded'});await page.evaluate(()=>localStorage.clear())});
test('v4.6 keeps the guest-first recommendation and auth journey',async({page})=>{const errs=await boot(page);await expect(page.locator('meta[name="footmate-release"]')).toHaveAttribute('content','4.6.0');await setup(page);const match=page.locator('.fm-next-match-card').first();const matchId=await match.getAttribute('data-match-id');await match.click();await page.getByRole('button',{name:'참가하기'}).click();await page.getByRole('textbox',{name:'아이디 또는 이메일'}).fill('member@example.com');await page.getByLabel('비밀번호',{exact:true}).fill('password123!');await page.getByRole('button',{name:'로그인'}).click();await expect(page.locator('[data-screen="checkout"]')).toBeVisible();expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('footmate:v4:session')||'{}').selectedMatchId)).toBe(matchId);expect(errs).toEqual([])});
test('v4.6 keeps real guided and evidence modes isolated',async({page})=>{let errs=await boot(page);await setup(page);await expect(page.locator('.fm-next-guide')).toHaveCount(0);expect(errs).toEqual([]);errs=failures(page);await page.setViewportSize({width:1280,height:900});await page.goto('/app?mode=guided',{waitUntil:'domcontentloaded'});await expect(page.getByText('Guided Case Study')).toBeVisible();await page.goto('/app?mode=evidence',{waitUntil:'domcontentloaded'});await expect(page.getByText('EVIDENCE MODE',{exact:true})).toBeVisible();expect(errs).toEqual([])});
test('v4.6 remains responsive and accessible at supported widths',async({page})=>{for(const width of [320,375,390,430]){const errs=await boot(page,'/app',{width,height:780});expect(await page.evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth)).toBeLessThanOrEqual(1);expect(errs).toEqual([]);await page.evaluate(()=>localStorage.clear())}const errs=await boot(page);await setup(page);const result=await new AxeBuilder({page}).include('.fm-next-app').withTags(['wcag2a','wcag2aa']).analyze();expect(result.violations.filter(v=>['serious','critical'].includes(v.impact))).toEqual([]);expect(errs).toEqual([])});
test('compatibility aliases resolve to v4.6',async({page})=>{for(const route of ['/demo','/next']){await page.goto(route,{waitUntil:'domcontentloaded'});await expect(page.locator('meta[name="footmate-release"]')).toHaveAttribute('content','4.6.0')}});
