const {test,expect}=require('@playwright/test');
const AxeBuilder=require('@axe-core/playwright').default;
function failures(page){const items=[];page.on('pageerror',e=>items.push(`pageerror: ${e.message}`));page.on('console',m=>{if(m.type()==='error'&&!m.text().includes('Failed to load resource'))items.push(`console.error: ${m.text()}`)});return items}
async function boot(page,path='/app',viewport={width:390,height:844}){const errs=failures(page);await page.setViewportSize(viewport);await page.goto(path,{waitUntil:'domcontentloaded'});await page.waitForSelector('#footmate-next [data-screen]');return errs}
async function serious(page){const result=await new AxeBuilder({page}).include('.fm-next-app').withTags(['wcag2a','wcag2aa']).analyze();return result.violations.filter(v=>['serious','critical'].includes(v.impact))}
async function setup(page){await page.getByRole('button',{name:/내 경기 찾아보기/}).click();await page.getByRole('button',{name:'다음'}).click();await page.getByRole('button',{name:'다음'}).click();await page.getByRole('button',{name:/추천 경기 보기/}).click();await expect(page.locator('[data-screen="home"]')).toBeVisible()}
test.beforeEach(async({page})=>{await page.goto('/app',{waitUntil:'domcontentloaded'});await page.evaluate(()=>localStorage.clear())});

test('v4.9 exposes the v5 release candidate contract and keeps the guest-first journey',async({page})=>{const errs=await boot(page);await expect(page.locator('meta[name="footmate-release"]')).toHaveAttribute('content','4.9.0');await expect(page.locator('#footmate-next')).toHaveAttribute('data-platform-version','4.9.0');await expect(page.locator('#footmate-next')).toHaveAttribute('data-release-candidate-version','4.9.0');const rc=await page.evaluate(()=>({version:window.__FOOTMATE_RELEASE_CANDIDATE__?.version,ready:window.__FOOTMATE_RELEASE_CANDIDATE__?.readyForV5,providerMode:window.__FOOTMATE_RELEASE_CANDIDATE__?.providerMode,externalProviders:window.__FOOTMATE_RELEASE_CANDIDATE__?.externalProviders,externalAnalytics:window.__FOOTMATE_RELEASE_CANDIDATE__?.externalAnalytics}));expect(rc).toEqual({version:'4.9.0',ready:true,providerMode:'mock-only',externalProviders:false,externalAnalytics:false});await setup(page);const match=page.locator('.fm-next-match-card').first();const matchId=await match.getAttribute('data-match-id');await match.click();await page.getByRole('button',{name:'참가하기'}).click();await page.getByRole('textbox',{name:'아이디 또는 이메일'}).fill('member@example.com');await page.getByLabel('비밀번호',{exact:true}).fill('password123!');await page.getByRole('button',{name:'로그인'}).click();await expect(page.locator('[data-screen="checkout"]')).toBeVisible();expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('footmate:v4:session')||'{}').selectedMatchId)).toBe(matchId);expect(errs).toEqual([])});

test('v4.9 full decision flow has no serious or critical axe violations',async({page})=>{const errs=await boot(page);expect(await serious(page)).toEqual([]);await page.getByRole('button',{name:/내 경기 찾아보기/}).click();expect(await serious(page)).toEqual([]);await page.getByRole('button',{name:'다음'}).click();await page.getByRole('button',{name:'다음'}).click();await page.getByRole('button',{name:/추천 경기 보기/}).click();await expect(page.locator('[data-screen="home"]')).toBeVisible();expect(await serious(page)).toEqual([]);await page.locator('.fm-next-match-card').first().click();await expect(page.locator('[data-screen="detail"]')).toBeVisible();expect(await serious(page)).toEqual([]);await page.getByRole('button',{name:'참가하기'}).click();await expect(page.locator('[data-screen="auth"]')).toBeVisible();expect(await serious(page)).toEqual([]);await page.getByRole('textbox',{name:'아이디 또는 이메일'}).fill('member@example.com');await page.getByLabel('비밀번호',{exact:true}).fill('password123!');await page.getByRole('button',{name:'로그인'}).click();await expect(page.locator('[data-screen="checkout"]')).toBeVisible();expect(await serious(page)).toEqual([]);expect(errs).toEqual([])});

test('v4.9 keeps modes and supported widths isolated and overflow-safe',async({page})=>{for(const width of [320,375,390,430]){const errs=await boot(page,'/app',{width,height:780});expect(await page.evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth)).toBeLessThanOrEqual(1);expect(errs).toEqual([]);await page.evaluate(()=>localStorage.clear())}await page.setViewportSize({width:1280,height:900});await page.goto('/app?mode=guided',{waitUntil:'domcontentloaded'});await expect(page.getByText('Guided Case Study')).toBeVisible();await page.goto('/app?mode=evidence',{waitUntil:'domcontentloaded'});await expect(page.getByText('EVIDENCE MODE',{exact:true})).toBeVisible()});

test('compatibility aliases resolve to v4.9',async({page})=>{for(const route of ['/demo','/next']){await page.goto(route,{waitUntil:'domcontentloaded'});await expect(page.locator('meta[name="footmate-release"]')).toHaveAttribute('content','4.9.0')}});
