const {test,expect}=require('@playwright/test');
const AxeBuilder=require('@axe-core/playwright').default;
function failures(page){const items=[];page.on('pageerror',e=>items.push(`pageerror: ${e.message}`));page.on('console',m=>{if(m.type()==='error'&&!m.text().includes('Failed to load resource'))items.push(`console.error: ${m.text()}`)});return items}
async function boot(page,path='/app',viewport={width:390,height:844}){const errs=failures(page);await page.setViewportSize(viewport);await page.goto(path,{waitUntil:'domcontentloaded'});await page.waitForSelector('#footmate-next [data-screen]');return errs}
async function setup(page){await page.getByRole('button',{name:/내 경기 찾아보기/}).click();await page.getByRole('button',{name:'다음'}).click();await page.getByRole('button',{name:'다음'}).click();await page.getByRole('button',{name:/추천 경기 보기/}).click();await expect(page.locator('[data-screen="home"]')).toBeVisible()}
async function auth(page){await setup(page);await page.locator('.fm-next-match-card').first().click();await page.getByRole('button',{name:'참가하기'}).click();await expect(page.locator('[data-screen="auth"]')).toBeVisible()}
test.beforeEach(async({page})=>{await page.goto('/app',{waitUntil:'domcontentloaded'});await page.evaluate(()=>localStorage.clear())});

test('v4 official release is guest-first and hides portfolio identity',async({page})=>{const errs=await boot(page);await expect(page.locator('meta[name="footmate-release"]')).toHaveAttribute('content','4.0.0');await expect(page.getByText('둘러보는 데 계정이 필요하지 않아요.')).toBeVisible();await setup(page);await expect(page.locator('.fm-next-match-card')).toHaveCount(2);await expect(page.locator('.fm-next-greeting')).not.toContainText('도현');await page.getByRole('button',{name:'내 정보'}).click();await expect(page.locator('.fm-next-profile-head')).toContainText('게스트');expect(errs).toEqual([])});

test('v4 validates account input and preserves selected match through checkout',async({page})=>{const errs=await boot(page);await auth(page);const login=page.getByRole('button',{name:'로그인'});await login.click();await expect(page.locator('.fm-auth-error')).toHaveCount(2);await page.getByRole('textbox',{name:'아이디 또는 이메일'}).fill('member@example.com');await page.getByLabel('비밀번호',{exact:true}).fill('password123!');await login.click();await expect(page.locator('[data-screen="checkout"]')).toBeVisible();await page.getByRole('button',{name:/결제하고 참가 확정/}).click();await expect(page.locator('[data-screen="success"]')).toBeVisible();expect(errs).toEqual([])});

test('v4 detail back returns to entry surface',async({page})=>{const errs=await boot(page);await setup(page);await page.locator('.fm-next-match-card').first().click();await page.getByRole('button',{name:'이전 화면'}).click();await expect(page.locator('[data-screen="home"]')).toBeVisible();await page.getByRole('button',{name:'전체 보기'}).click();await page.locator('.fm-next-match-card').first().click();await page.getByRole('button',{name:'이전 화면'}).click();await expect(page.locator('[data-screen="discover"]')).toBeVisible();expect(errs).toEqual([])});

test('v4 matchday check-in persists across reload',async({page})=>{const errs=await boot(page,'/app?mode=evidence',{width:1280,height:900});await page.getByRole('button',{name:'경기 당일'}).click();await page.getByRole('button',{name:'체크인하기'}).click();await expect(page.getByRole('button',{name:'체크인 완료'})).toBeDisabled();await page.reload({waitUntil:'domcontentloaded'});await page.getByRole('button',{name:'경기 당일'}).click();await expect(page.getByRole('button',{name:'체크인 완료'})).toBeDisabled();expect(errs).toEqual([])});

test('v4 real/guided/evidence modes remain isolated',async({page})=>{let errs=await boot(page);await setup(page);await expect(page.locator('.fm-next-guide')).toHaveCount(0);await expect(page.getByText('EVIDENCE MODE',{exact:true})).toHaveCount(0);expect(errs).toEqual([]);errs=failures(page);await page.goto('/app?mode=guided',{waitUntil:'domcontentloaded'});await expect(page.getByText('Guided Case Study')).toBeVisible();await page.goto('/app?mode=evidence',{waitUntil:'domcontentloaded'});await expect(page.getByText('EVIDENCE MODE',{exact:true})).toBeVisible();expect(errs).toEqual([])});

test('v4 remains responsive and accessible at supported mobile widths',async({page})=>{for(const width of [320,375,390,430]){const errs=await boot(page,'/app',{width,height:780});expect(await page.evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth)).toBeLessThanOrEqual(1);await setup(page);const heights=await page.locator('.fm-next-nav button').evaluateAll(nodes=>nodes.map(n=>n.getBoundingClientRect().height));heights.forEach(h=>expect(h).toBeGreaterThanOrEqual(44));expect(errs).toEqual([]);await page.evaluate(()=>localStorage.clear())}const errs=await boot(page);await setup(page);const result=await new AxeBuilder({page}).include('.fm-next-app').withTags(['wcag2a','wcag2aa']).analyze();expect(result.violations.filter(v=>['serious','critical'].includes(v.impact))).toEqual([]);expect(errs).toEqual([])});

test('v4 Case Study is official, product-first and mobile-safe',async({page})=>{const errs=failures(page);await page.setViewportSize({width:1440,height:900});await page.goto('/',{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>document.querySelectorAll('.slide').length===16&&document.querySelector('.fm-next-cover'));await expect(page.locator('.slide')).toHaveCount(16);await expect(page.locator('.fm-next-cover-note')).toContainText('v4.0.0');await expect(page.locator('.fm-next-cover-frame iframe')).toHaveAttribute('src','/app?embed=1');expect((await page.locator('body').innerText()).toLowerCase()).not.toContain('next major candidate');await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth)).toBeLessThanOrEqual(1);expect(errs).toEqual([])});

test('legacy public routes resolve to the v4 surface',async({page})=>{for(const route of ['/demo','/next']){await page.goto(route,{waitUntil:'domcontentloaded'});await expect(page.locator('meta[name="footmate-release"]')).toHaveAttribute('content','4.0.0');await expect(page.getByRole('heading',{name:/내 수준에 맞는 경기부터/})).toBeVisible()}});
