const {test,expect}=require('@playwright/test');
const AxeBuilder=require('@axe-core/playwright').default;
function failures(page){const items=[];page.on('pageerror',e=>items.push(`pageerror: ${e.message}`));page.on('console',m=>{if(m.type()==='error'&&!m.text().includes('Failed to load resource'))items.push(`console.error: ${m.text()}`)});return items}
async function boot(page,path='/app',viewport={width:390,height:844}){const errs=failures(page);await page.setViewportSize(viewport);await page.goto(path,{waitUntil:'domcontentloaded'});await page.waitForSelector('#footmate-next [data-screen]');await page.waitForFunction(()=>window.__FOOTMATE_V5__?.version==='5.0.0');return errs}
async function serious(page){const result=await new AxeBuilder({page}).include('.fm-next-app').withTags(['wcag2a','wcag2aa']).analyze();return result.violations.filter(v=>['serious','critical'].includes(v.impact))}
async function setup(page){await page.getByRole('button',{name:/내 경기 찾아보기/}).click();await page.getByRole('button',{name:'다음'}).click();await page.getByRole('button',{name:'다음'}).click();await page.getByRole('button',{name:/추천 경기 보기/}).click();await expect(page.locator('[data-screen="home"]')).toBeVisible()}
test.beforeEach(async({page})=>{await page.goto('/app',{waitUntil:'domcontentloaded'});await page.evaluate(()=>localStorage.clear())});

test('v5.0 exposes connected-capable architecture without claiming external providers',async({page})=>{const errs=await boot(page);await expect(page.locator('meta[name="footmate-release"]')).toHaveAttribute('content','5.0.0');await expect(page.locator('#footmate-next')).toHaveAttribute('data-connected-platform-version','5.0.0');await expect(page.locator('#footmate-next')).toHaveAttribute('data-connection-mode','mock-only');const v5=await page.evaluate(()=>({version:window.__FOOTMATE_V5__?.version,architecture:window.__FOOTMATE_V5__?.architecture,connectionMode:window.__FOOTMATE_V5__?.connectionMode,connected:window.__FOOTMATE_V5__?.connectedProviders,mocks:window.__FOOTMATE_V5__?.mockProviders,external:window.__FOOTMATE_V5__?.externalProductionFeatures,domains:window.__FOOTMATE_V5__?.domains}));expect(v5).toEqual({version:'5.0.0',architecture:'connected-capable',connectionMode:'mock-only',connected:[],mocks:['auth','payment','capacity','notification'],external:false,domains:['recommendation','participation','matchday','return']});expect(errs).toEqual([])});

test('v5.0 full decision flow keeps accessibility and selected-match continuity',async({page})=>{const errs=await boot(page);expect(await serious(page)).toEqual([]);await page.getByRole('button',{name:/내 경기 찾아보기/}).click();expect(await serious(page)).toEqual([]);await page.getByRole('button',{name:'다음'}).click();await page.getByRole('button',{name:'다음'}).click();await page.getByRole('button',{name:/추천 경기 보기/}).click();await expect(page.locator('[data-screen="home"]')).toBeVisible();expect(await serious(page)).toEqual([]);const match=page.locator('.fm-next-match-card').first();const matchId=await match.getAttribute('data-match-id');await match.click();await expect(page.locator('[data-screen="detail"]')).toBeVisible();expect(await serious(page)).toEqual([]);await page.getByRole('button',{name:'참가하기'}).click();await expect(page.locator('[data-screen="auth"]')).toBeVisible();expect(await serious(page)).toEqual([]);await page.getByRole('textbox',{name:'아이디 또는 이메일'}).fill('member@example.com');await page.getByLabel('비밀번호',{exact:true}).fill('password123!');await page.getByRole('button',{name:'로그인'}).click();await expect(page.locator('[data-screen="checkout"]')).toBeVisible();expect(await serious(page)).toEqual([]);expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('footmate:v4:session')||'{}').selectedMatchId)).toBe(matchId);expect(errs).toEqual([])});

test('v5.0 cross-domain guardrail accepts a consistent journey and rejects mismatched ownership',async({page})=>{await boot(page);const result=await page.evaluate(()=>({good:window.__FOOTMATE_V5__.evaluateJourney({recommendation:{selectedMatchId:'m1'},participation:{status:'success',matchId:'m1'},matchday:{status:'checked-in',matchId:'m1'},returnState:{completed:true,matchId:'m1'}}),bad:window.__FOOTMATE_V5__.evaluateJourney({recommendation:{selectedMatchId:'m1'},participation:{status:'success',matchId:'m2'},matchday:{status:'checked-in',matchId:'m2'},returnState:{completed:true,matchId:'m3'}})}));expect(result.good.valid).toBe(true);expect(result.bad.valid).toBe(false);expect(result.bad.problems).toContain('selected-participation-mismatch');expect(result.bad.problems).toContain('matchday-return-mismatch')});

test('v5.0 preserves responsive runtime, reviewer modes and compatibility routes',async({page})=>{for(const width of [320,375,390,430]){const errs=await boot(page,'/app',{width,height:780});expect(await page.evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth)).toBeLessThanOrEqual(1);expect(errs).toEqual([]);await page.evaluate(()=>localStorage.clear())}await page.setViewportSize({width:1280,height:900});await page.goto('/app?mode=guided',{waitUntil:'domcontentloaded'});await expect(page.getByText('Guided Case Study')).toBeVisible();await page.goto('/app?mode=evidence',{waitUntil:'domcontentloaded'});await expect(page.getByText('EVIDENCE MODE',{exact:true})).toBeVisible();for(const route of ['/demo','/next']){await page.goto(route,{waitUntil:'domcontentloaded'});await expect(page.locator('meta[name="footmate-release"]')).toHaveAttribute('content','5.0.0')}});
