const {test,expect}=require('@playwright/test');
const AxeBuilder=require('@axe-core/playwright').default;
async function setup(page){await page.goto('/app',{waitUntil:'domcontentloaded'});await page.evaluate(()=>{localStorage.clear();sessionStorage.clear()});await page.reload({waitUntil:'domcontentloaded'});await page.getByRole('button',{name:/내 경기 찾아보기/}).click();await page.getByRole('button',{name:'다음'}).click();await page.getByRole('button',{name:'다음'}).click();await page.getByRole('button',{name:/추천 경기 보기/}).click();await expect(page.locator('[data-screen="home"]')).toBeVisible();await expect(page.locator('[data-ai-assistant="5.1.1"]')).toBeVisible()}

test('v5.1.1 AI Match Assistant falls back to rules when local API is unavailable',async({page})=>{await setup(page);await page.getByLabel('찾고 싶은 경기 조건').fill('20분 안쪽에서 GK 자리 있는 경기');await page.getByRole('button',{name:'AI로 찾기'}).click();await expect(page.locator('[data-ai-mode]')).toHaveText('Rules fallback');await expect(page.locator('[data-screen="home"]')).toBeVisible();await expect(page.locator('[data-ai-conditions]')).toContainText('GK');await expect(page.locator('[data-ai-conditions]')).toContainText('20분 이내');await expect(page.locator('.fm-ai-result').first()).toBeHidden();await expect(page.locator('.fm-product-ai-retry')).toBeVisible();const runtime=await page.evaluate(()=>({version:window.__FOOTMATE_AI__?.version,mode:window.__FOOTMATE_AI__?.mode,rankingOwner:window.__FOOTMATE_AI__?.rankingOwner,timeout:window.__FOOTMATE_AI__?.requestTimeoutMs,hitl:window.__FOOTMATE_AI__?.hitl}));expect(runtime).toEqual({version:'5.1.1',mode:'rules-fallback',rankingOwner:'deterministic recommendation engine',timeout:7000,hitl:['join','payment']})});

test('v5.1.1 AI state hierarchy distinguishes loading and fallback without duplicating results on Home',async({page})=>{await page.route('**/api/ai-match-assistant',async route=>{await new Promise(resolve=>setTimeout(resolve,450));await route.fulfill({status:503,contentType:'application/json',body:'{}'})});await setup(page);const input=page.getByLabel('찾고 싶은 경기 조건'),button=page.getByRole('button',{name:'AI로 찾기'});await input.fill('21시 이후 11000원 이하 GK 경기');await button.click();const loading=page.locator('.fm-ai-loading');await expect(loading).toBeVisible();await expect(page.locator('[data-ai-mode]')).toHaveText('Rules fallback');await expect(page.locator('[data-screen="home"]')).toBeVisible();await expect(page.locator('.fm-ai-empty')).toBeHidden();await expect(page.locator('.fm-product-ai-retry')).toBeVisible();await expect(input).toBeEnabled();await expect(button).toBeEnabled()});

test('v5.1.1 connected AI response only supplies constraints while deterministic engine owns results',async({page})=>{await page.route('**/api/ai-match-assistant',route=>route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({version:'5.1.1',mode:'connected-ai',provider:'vercel-ai-gateway',model:'openai/gpt-5.4-mini',fallbackUsed:false,result:{intent:'search',region:'수원 · 인계',position:null,level:'초중급',maxPrice:12000,maxDistanceMin:null,afterTime:null,reply:'수원 인계의 초중급, 12,000원 이하 조건으로 정리했어요.'}})}));await setup(page);await page.getByLabel('찾고 싶은 경기 조건').fill('인계에서 초중급 12000원 이하 경기');await page.getByRole('button',{name:'AI로 찾기'}).click();await expect(page.locator('[data-screen="discover"]')).toBeVisible();await expect(page.locator('[data-ai-mode]')).toHaveText('AI connected');await expect(page.locator('[data-ia-ai-summary]')).toContainText('수원 · 인계');await expect(page.locator('[data-ia-ai-summary]')).toContainText('초급');await expect(page.locator('[data-ia-ai-summary]')).toContainText('12,000원 이하');await expect(page.locator('[data-screen="discover"] .fm-next-match-card:visible').first()).toBeVisible();expect(await page.evaluate(()=>window.__FOOTMATE_AI__.mode)).toBe('connected-ai')});

test('v5.1.1 AI request timeout recovers to deterministic rules and restores controls',async({page})=>{await page.route('**/api/ai-match-assistant',async route=>{await new Promise(resolve=>setTimeout(resolve,7600));try{await route.fulfill({status:200,contentType:'application/json',body:'{}'})}catch{}});await setup(page);const input=page.getByLabel('찾고 싶은 경기 조건'),button=page.getByRole('button',{name:'AI로 찾기'});await input.fill('수원 인계에서 가까운 중급 경기');await button.click();await expect(page.locator('[data-ai-mode]')).toHaveText('Rules fallback',{timeout:10000});await expect(input).toBeEnabled();await expect(button).toBeEnabled();expect(await page.evaluate(()=>window.__FOOTMATE_AI__.mode)).toBe('rules-fallback')});

test('v5.1.1 internal resume restores saved AI mode consistently while fresh entry still resets',async({page})=>{await page.route('**/api/ai-match-assistant',route=>route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({version:'5.1.1',mode:'connected-ai',provider:'vercel-ai-gateway',model:'openai/gpt-5.4-mini',fallbackUsed:false,result:{intent:'search',region:'수원 · 인계',position:'MF',level:'중급',maxPrice:null,maxDistanceMin:20,afterTime:null,reply:'수원 인계의 가까운 중급 MF 조건으로 정리했어요.'}})}));await setup(page);await page.getByLabel('찾고 싶은 경기 조건').fill('수원 인계에서 가까운 중급 MF 경기');await page.getByRole('button',{name:'AI로 찾기'}).click();await expect(page.locator('[data-screen="discover"]')).toBeVisible();await expect(page.locator('[data-ai-mode]')).toHaveText('AI connected');await page.goto('/app?resume=1',{waitUntil:'domcontentloaded'});await expect(page.locator('[data-ai-assistant="5.1.1"]')).toHaveCount(1);await expect(page.locator('[data-ai-mode]')).toHaveText('AI connected');expect(await page.evaluate(()=>window.__FOOTMATE_AI__.mode)).toBe('connected-ai')});

test('v5.1.1 AI assistant remains accessible and responsive',async({page})=>{for(const width of [320,375,390,430]){await page.setViewportSize({width,height:780});await setup(page);expect(await page.evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth)).toBeLessThanOrEqual(1);await page.evaluate(()=>{localStorage.clear();sessionStorage.clear()})}const axe=await new AxeBuilder({page}).include('[data-ai-assistant]').withTags(['wcag2a','wcag2aa']).analyze();expect(axe.violations.filter(v=>['serious','critical'].includes(v.impact))).toEqual([])});
