const {test,expect}=require('@playwright/test');
const AxeBuilder=require('@axe-core/playwright').default;
function failures(page){const items=[];page.on('pageerror',e=>items.push(`pageerror: ${e.message}`));page.on('console',m=>{if(m.type()==='error'&&!m.text().includes('Failed to load resource'))items.push(`console.error: ${m.text()}`)});return items}
async function boot(page,path='/app',viewport={width:390,height:844}){const errs=failures(page);await page.setViewportSize(viewport);await page.goto(path,{waitUntil:'domcontentloaded'});await page.waitForSelector('#footmate-next [data-screen]');await page.waitForFunction(()=>window.__FOOTMATE_V5__?.version==='5.1.1'&&window.__FOOTMATE_AI__?.version==='5.1.1');return errs}
async function serious(page){const result=await new AxeBuilder({page}).include('.fm-next-app').withTags(['wcag2a','wcag2aa']).analyze();return result.violations.filter(v=>['serious','critical'].includes(v.impact))}
async function setup(page){await page.getByRole('button',{name:/내 경기 찾아보기/}).click();await page.getByRole('button',{name:'다음'}).click();await page.getByRole('button',{name:'다음'}).click();await page.getByRole('button',{name:/추천 경기 보기/}).click();await expect(page.locator('[data-screen="home"]')).toBeVisible()}
test.beforeEach(async({page})=>{await page.goto('/app',{waitUntil:'domcontentloaded'});await page.evaluate(()=>localStorage.clear())});

test('v5.1.1 keeps connected platform contracts and a version-neutral product surface',async({page})=>{const errs=await boot(page);await expect(page).toHaveTitle('FootMate | AI-assisted Futsal Match Discovery');await expect(page.locator('meta[name="footmate-release"]')).toHaveAttribute('content','5.2.0');await expect(page.locator('#footmate-next')).toHaveAttribute('data-connected-platform-version','5.1.1');await expect(page.locator('#footmate-next')).toHaveAttribute('data-connection-mode','mock-only');await expect(page.locator('#footmate-next')).toHaveAttribute('data-ai-assistant','available');const runtime=await page.evaluate(()=>({v5:window.__FOOTMATE_V5__?.version,architecture:window.__FOOTMATE_V5__?.architecture,mode:window.__FOOTMATE_V5__?.connectionMode,mocks:window.__FOOTMATE_V5__?.mockProviders,ai:window.__FOOTMATE_AI__?.version,workflow:window.__FOOTMATE_AI__?.workflow,rankingOwner:window.__FOOTMATE_AI__?.rankingOwner}));expect(runtime).toEqual({v5:'5.1.1',architecture:'connected-capable',mode:'mock-only',mocks:['auth','payment','capacity','notification'],ai:'5.1.1',workflow:'Context → Plan → Tools → Guardrail → Observe',rankingOwner:'deterministic recommendation engine'});expect(errs).toEqual([])});

test('v5.1.1 preserves recommendation through checkout continuity and accessibility',async({page})=>{const errs=await boot(page);expect(await serious(page)).toEqual([]);await setup(page);expect(await serious(page)).toEqual([]);const match=page.locator('.fm-next-match-card').first();const matchId=await match.getAttribute('data-match-id');await match.click();await expect(page.locator('[data-screen="detail"]')).toBeVisible();expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('footmate:v4:session')||'{}').selectedMatchId)).toBe(matchId);expect(await serious(page)).toEqual([]);await page.getByRole('button',{name:'참가하기'}).click();await expect(page.locator('[data-screen="auth"]')).toBeVisible();expect(await serious(page)).toEqual([]);await page.getByRole('textbox',{name:'아이디'}).fill('member01');await page.getByLabel('비밀번호',{exact:true}).fill('password123!');await page.getByRole('button',{name:'로그인'}).click();await expect(page.locator('[data-screen="checkout"]')).toBeVisible();expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('footmate:v4:session')||'{}').selectedMatchId)).toBe(matchId);expect(await serious(page)).toEqual([]);expect(errs).toEqual([])});

test('v5.1.1 cross-domain consistency guardrail remains intact',async({page})=>{await boot(page);const result=await page.evaluate(()=>({good:window.__FOOTMATE_V5__.evaluateJourney({recommendation:{selectedMatchId:'m1'},participation:{status:'success',matchId:'m1'},matchday:{status:'checked-in',matchId:'m1'},returnState:{completed:true,matchId:'m1'}}),bad:window.__FOOTMATE_V5__.evaluateJourney({recommendation:{selectedMatchId:'m1'},participation:{status:'success',matchId:'m2'},matchday:{status:'checked-in',matchId:'m2'},returnState:{completed:true,matchId:'m3'}})}));expect(result.good.valid).toBe(true);expect(result.bad.valid).toBe(false);expect(result.bad.problems).toContain('selected-participation-mismatch');expect(result.bad.problems).toContain('matchday-return-mismatch')});

test('v5.1.1 preserves responsive modes and compatibility routes',async({page})=>{for(const width of [320,375,390,430]){const errs=await boot(page,'/app',{width,height:780});expect(await page.evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth)).toBeLessThanOrEqual(1);expect(errs).toEqual([]);await page.evaluate(()=>localStorage.clear())}await page.setViewportSize({width:1280,height:900});await page.goto('/app?mode=guided',{waitUntil:'domcontentloaded'});await expect(page.getByText('Guided Case Study')).toBeVisible();await page.goto('/app?mode=evidence',{waitUntil:'domcontentloaded'});await expect(page.getByText('EVIDENCE MODE',{exact:true})).toBeVisible();for(const route of ['/demo','/next']){await page.goto(route,{waitUntil:'domcontentloaded'});await expect(page.locator('meta[name="footmate-release"]')).toHaveAttribute('content','5.2.0')}});
