import {MATCHES,createState} from './data.js';
import {footmatePlatform} from './platform/application/platform.js';

const RETURN_VERSION='4.6.0';
const RETURN_STORAGE_KEY=footmatePlatform.storageKeys.returnLoop;
const returnRepository=footmatePlatform.repositories.returnLoop;
const root=document.getElementById('footmate-next');
const LEVELS=['입문','초중급','중급','중급+'];

function readSession(){return createState(footmatePlatform.session.read()||{})}
function readReturn(){const value=returnRepository.read({})||{};return {version:RETURN_VERSION,history:Array.isArray(value.history)?value.history:[],draft:value.draft&&typeof value.draft==='object'?value.draft:null}}
function writeReturn(next){const value={version:RETURN_VERSION,history:next.history||[],draft:next.draft||null};returnRepository.write(value);return value}
function updateSession(patch){const next={...readSession(),...patch};footmatePlatform.session.write(next);return next}
function currentMatch(session=readSession()){return MATCHES.find(match=>match.id===session.joinedMatchId)||null}
function latestFeedback(state=readReturn()){return state.history[state.history.length-1]||null}
function targetLevel(feedback){if(!feedback)return null;const match=MATCHES.find(item=>item.id===feedback.matchId);if(!match)return null;const index=LEVELS.indexOf(match.level);if(index<0)return match.level;if(feedback.difficulty==='hard')return LEVELS[Math.max(0,index-1)];if(feedback.difficulty==='easy')return LEVELS[Math.min(LEVELS.length-1,index+1)];return match.level}
function feedbackRank(preferences={}){const session=createState({...readSession(),...preferences});const base=window.__FOOTMATE_RECOMMENDATION__?.rank?.(session)||[];const feedback=latestFeedback();if(!feedback)return base.map(item=>({...item,baseScore:item.score,adjustment:0}));const played=MATCHES.find(match=>match.id===feedback.matchId);const target=targetLevel(feedback);return base.map(item=>{const match=MATCHES.find(value=>value.id===item.id);let adjustment=0;if(match?.level===target)adjustment+=10;if(feedback.repeatIntent&&played&&match?.region===played.region)adjustment+=5;if(feedback.repeatIntent&&played&&match?.format===played.format)adjustment+=3;if(match?.id===feedback.matchId)adjustment-=20;return {...item,baseScore:item.score,adjustment,score:item.score+adjustment}}).sort((a,b)=>b.score-a.score||b.adjustment-a.adjustment||a.id.localeCompare(b.id))}
function difficultyLabel(value){return {easy:'쉬웠어요',expected:'적당했어요',hard:'어려웠어요'}[value]||'선택 전'}
function draftFor(matchId,state=readReturn()){return state.draft?.matchId===matchId?state.draft:{matchId,difficulty:null,repeatIntent:null}}
function panel(){const session=readSession();const match=currentMatch(session);if(!match||session.matchStage!=='postgame')return '';const state=readReturn();const existing=state.history.find(item=>item.matchId===match.id);const draft=draftFor(match.id,state);if(existing){const next=feedbackRank().find(item=>item.id!==match.id);const nextMatch=MATCHES.find(item=>item.id===next?.id);return `<section class="fm-return-panel" data-return-version="${RETURN_VERSION}" data-return-state="saved" aria-label="경기 후 피드백"><div class="fm-return-kicker">RETURN LOOP · ${RETURN_VERSION}</div><div class="fm-return-status" role="status"><b>경기 기록을 저장했어요</b><span>${match.place} · 체감 난이도 ${difficultyLabel(existing.difficulty)}</span></div><div class="fm-return-summary"><article><small>참여 이력</small><b>${state.history.length}회 완료</b></article><article><small>다음 추천 보조 신호</small><b>${nextMatch?nextMatch.place:'새 경기를 탐색해보세요'}</b></article></div><p class="fm-return-boundary">이 기록은 개인 히스토리와 다음 추천을 돕는 로컬 신호입니다. 공개 평판·신뢰도 점수로 노출하지 않으며 외부 reputation backend는 연결하지 않았습니다.</p></section>`}const diff=(value,label)=>`<button type="button" data-return-action="difficulty" data-value="${value}" aria-pressed="${draft.difficulty===value}">${label}</button>`;const repeat=(value,label)=>`<button type="button" data-return-action="repeat" data-value="${value}" aria-pressed="${String(draft.repeatIntent)===value}">${label}</button>`;return `<section class="fm-return-panel" data-return-version="${RETURN_VERSION}" data-return-state="draft" aria-label="경기 후 피드백"><div class="fm-return-kicker">RETURN LOOP · ${RETURN_VERSION}</div><div class="fm-return-status"><b>오늘 경기, 어땠나요?</b><span>체감 난이도와 다시 뛰고 싶은 조건을 남기면 다음 경기 정렬에 보조 신호로 반영합니다.</span></div><fieldset class="fm-return-field"><legend>체감 난이도</legend><div class="fm-return-options">${diff('easy','쉬웠어요')}${diff('expected','적당했어요')}${diff('hard','어려웠어요')}</div></fieldset><fieldset class="fm-return-field"><legend>비슷한 경기 다시 추천</legend><div class="fm-return-options fm-return-options--two">${repeat('true','네, 비슷한 경기')}${repeat('false','다른 조건 탐색')}</div></fieldset><button class="fm-return-save" type="button" data-return-action="save" ${!draft.difficulty||draft.repeatIntent===null?'disabled':''}>평가 저장</button><p class="fm-return-boundary">개인 피드백과 참여 완료 이력만 저장합니다. 팀원 평가나 공개 스포츠맨십 점수를 만들지 않으며 데이터는 이 프로토타입의 브라우저에만 남습니다.</p></section>`}
function historyStrip(){const state=readReturn();if(!state.history.length)return '';return `<section class="fm-return-history" data-return-history><small>RETURN HISTORY</small><b>완료한 경기 ${state.history.length}회</b><span>개인 참여 이력 · 공개 평판 점수 아님</span></section>`}
function saveDraft(patch){const state=readReturn();const session=readSession();const match=currentMatch(session);if(!match)return state;return writeReturn({...state,draft:{...draftFor(match.id,state),...patch}})}
function saveFeedback(){const state=readReturn();const session=readSession();const match=currentMatch(session);if(!match)return state;const draft=draftFor(match.id,state);if(!draft.difficulty||draft.repeatIntent===null)return state;const entry={matchId:match.id,completed:true,difficulty:draft.difficulty,repeatIntent:Boolean(draft.repeatIntent),submittedAt:new Date().toISOString()};const history=[...state.history.filter(item=>item.matchId!==match.id),entry];return writeReturn({history,draft:null})}
function enhancePanel(){if(!root)return;const session=readSession();const schedule=root.querySelector('[data-screen="schedule"]');if(schedule&&session.matchStage==='postgame'&&currentMatch(session)){const existing=schedule.querySelector('[data-return-version]');const nextState=readReturn().history.some(item=>item.matchId===session.joinedMatchId)?'saved':'draft';if(!existing){const section=schedule.querySelector('.fm-next-section')||schedule;section.insertAdjacentHTML('afterbegin',panel())}else if(existing.dataset.returnState!==nextState)existing.outerHTML=panel()}const profile=root.querySelector('[data-screen="profile"]');if(profile&&readReturn().history.length&&!profile.querySelector('[data-return-history]')){const section=profile.querySelector('.fm-next-section')||profile;section.insertAdjacentHTML('afterbegin',historyStrip())}}
function enhanceRanking(){if(!root)return;const feedback=latestFeedback();if(!feedback)return;const ranked=feedbackRank();const order=new Map(ranked.map((item,index)=>[item.id,{index,item}]));for(const screen of root.querySelectorAll('[data-screen="home"],[data-screen="discover"]')){const list=screen.querySelector('.fm-next-list');if(!list)continue;const sig=`${feedback.matchId}|${feedback.submittedAt}|${feedback.difficulty}|${feedback.repeatIntent}`;if(list.dataset.fmReturnSignature===sig)continue;list.dataset.fmReturnSignature=sig;const cards=[...list.querySelectorAll('.fm-next-match-card')];cards.sort((a,b)=>(order.get(a.dataset.matchId)?.index??999)-(order.get(b.dataset.matchId)?.index??999));cards.forEach(card=>{const info=order.get(card.dataset.matchId)?.item;if(!info)return;card.dataset.returnAdjustment=String(info.adjustment);if(info.adjustment>0&&!card.querySelector('.fm-return-reason')){const body=card.querySelector('.fm-next-match-body')||card;body.insertAdjacentHTML('afterbegin',`<span class="fm-return-reason">경기 후 피드백 반영 +${info.adjustment}</span>`)}list.appendChild(card)})}}
function rerenderPanel(){const existing=root?.querySelector('[data-return-version]');if(existing)existing.outerHTML=panel();else enhancePanel()}
function enhance(){enhancePanel();enhanceRanking();if(root)root.dataset.returnVersion=RETURN_VERSION}

document.addEventListener('click',event=>{const target=event.target.closest('[data-return-action],[data-action="rate-match"]');if(!target)return;if(target.matches('[data-action="rate-match"]')){const session=readSession();if(session.matchStage!=='postgame')return;event.preventDefault();event.stopPropagation();updateSession({route:'schedule'});location.reload();return}const action=target.dataset.returnAction;if(!action)return;event.preventDefault();event.stopPropagation();if(action==='difficulty'){saveDraft({difficulty:target.dataset.value});rerenderPanel();return}if(action==='repeat'){saveDraft({repeatIntent:target.dataset.value==='true'});rerenderPanel();return}if(action==='save'){saveFeedback();rerenderPanel();enhanceRanking();return}},true);
const observer=new MutationObserver(()=>requestAnimationFrame(enhance));if(root)observer.observe(root,{childList:true,subtree:true});
window.__FOOTMATE_RETURN__={version:RETURN_VERSION,storageKey:RETURN_STORAGE_KEY,read:readReturn,rank:feedbackRank,save:saveFeedback,reset:()=>{returnRepository.clear();enhance();return readReturn()}};
enhance();
