const root=document.getElementById('footmate-beta');
const SESSION_KEY='footmate:beta:auth:v1';
const TABLES=['matches','match_slots','participations','beta_notifications','beta_waitlist','beta_match_feedback'];
const POSITIONS={MF:'MF · 미드필더',FW:'FW · 공격수',DF:'DF · 수비수',GK:'GK · 골키퍼'};

if(root){
let config=null,profile=null,matches=[],participations=[],waitlist=[],feedback=[],recommendation=null;
let realtimeState='connecting',socket=null,heartbeat=null,reconnectTimer=null,busy=false,message='',refreshTimer=null;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]||c));
const session=()=>{try{return JSON.parse(localStorage.getItem(SESSION_KEY)||'null')}catch{return null}};
const accessToken=()=>String(session()?.accessToken||'');
const jwtUserId=()=>{try{const part=accessToken().split('.')[1]||'';const padded=(part.replace(/-/g,'+').replace(/_/g,'/')+'==='.slice((part.length+3)%4));return JSON.parse(atob(padded))?.sub||''}catch{return''}};
const startLabel=v=>new Intl.DateTimeFormat('ko-KR',{timeZone:'Asia/Seoul',month:'short',day:'numeric',weekday:'short',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date(v));
const headers=(auth=true)=>({apikey:config?.publishableKey||'',...(auth&&accessToken()?{authorization:`Bearer ${accessToken()}`}:{})});
async function request(path,{auth=true,...options}={}){const response=await fetch(`${config.url}${path}`,{...options,headers:{...headers(auth),...(options.headers||{})}});const data=await response.json().catch(()=>null);if(!response.ok)throw new Error(data?.message||data?.error_description||data?.error||`요청 실패 (${response.status})`);return data}
const rpc=(name,params)=>request(`/rest/v1/rpc/${name}`,{method:'POST',headers:{'content-type':'application/json',prefer:'return=representation'},body:JSON.stringify(params||{})});
async function loadConfig(){if(config)return;const res=await fetch('/api/beta-config',{cache:'no-store'});config=await res.json();if(!res.ok||!config?.connected)throw new Error('Beta backend config unavailable')}
async function loadState(){
 await loadConfig();
 const q='/rest/v1/matches?select=id,title,venue_name,area_label,address,region,level,positions,starts_at,price_krw,capacity_total,joined_count,remaining_spots,format_label,surface,duration_minutes,status,cancel_cutoff_at,check_in_opens_at,match_slots(position,capacity_total,joined_count,remaining_spots)&status=in.(open,full,completed)&order=starts_at.asc&limit=80';
 matches=await request(q,{auth:false});
 if(accessToken()){
  const uid=jwtUserId();
  const rows=await Promise.all([
   request(`/rest/v1/profiles?select=*&id=eq.${encodeURIComponent(uid)}&limit=1`).catch(()=>[]),
   request('/rest/v1/participations?select=*&order=created_at.desc').catch(()=>[]),
   request('/rest/v1/beta_waitlist?select=*&order=created_at.asc').catch(()=>[]),
   request('/rest/v1/beta_match_feedback?select=*&order=created_at.desc').catch(()=>[])
  ]);
  profile=rows[0]?.[0]||null;participations=rows[1]||[];waitlist=rows[2]||[];feedback=rows[3]||[];
 }else{profile=null;participations=[];waitlist=[];feedback=[]}
 render();
}
const slotLeft=(m,p)=>Number((m.match_slots||[]).find(x=>x.position===p)?.remaining_spots??0);
const queued=id=>waitlist.find(x=>x.match_id===id&&x.status==='queued');
const savedFeedback=id=>feedback.find(x=>x.match_id===id);
function matchesConstraint(m,r){
 if(!['open','full'].includes(m.status)||new Date(m.starts_at)<=new Date())return false;
 if(r.region&&m.region!==r.region)return false;if(r.position&&!(m.positions||[]).includes(r.position))return false;if(r.level&&m.level!==r.level)return false;
 if(r.maxPrice!=null&&Number(m.price_krw||0)>r.maxPrice)return false;
 if(r.afterTime){const t=new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Seoul',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date(m.starts_at));if(t<r.afterTime)return false}
 return true;
}
function rank(r){return matches.filter(m=>matchesConstraint(m,r)).map(m=>{let score=0,reasons=[];if(r.region){score+=40;reasons.push('생활권 일치')}if(r.position){const left=slotLeft(m,r.position);if(left>0){score+=30;reasons.push(`${r.position} ${left}자리`)}else reasons.push(`${r.position} 대기 가능`)}if(r.level){score+=20;reasons.push('레벨 일치')}if(Number(m.price_krw||0)===0){score+=5;reasons.push('Beta 무료')}return{m,score,reasons}}).sort((a,b)=>b.score-a.score||new Date(a.m.starts_at)-new Date(b.m.starts_at))}
async function recommend(form){const query=String(new FormData(form).get('query')||'').trim();if(!query)return;busy=true;message='';render();try{const res=await fetch('/api/ai-match-assistant',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({message:query,preferences:{region:profile?.region||null,position:profile?.position||null,level:profile?.level||null}})});const body=await res.json();if(!res.ok||!body?.result)throw new Error('AI 조건 해석을 완료하지 못했습니다.');recommendation={...body,ranked:rank(body.result)};if(body.result.maxDistanceMin!=null)message='실제 Beta 경기에는 이동시간 데이터가 없어 거리 조건은 순위에 사용하지 않았습니다.'}catch(e){recommendation=null;message=String(e?.message||e)}finally{busy=false;render()}}
async function waitlistAction(id,cancel){busy=true;render();try{if(cancel)await rpc('cancel_beta_waitlist',{p_match_id:id});else{if(!profile?.position)throw new Error('선호 포지션을 먼저 설정해주세요.');await rpc('join_beta_waitlist',{p_match_id:id,p_position:profile.position})}message=cancel?'대기 신청을 취소했습니다.':'대기 신청했습니다. 빈 자리가 생기면 자동 참가 전환됩니다.';await loadState()}catch(e){message=String(e?.message||e)}finally{busy=false;render()}}
async function submitFeedback(form){const data=new FormData(form);busy=true;render();try{await rpc('submit_beta_match_feedback',{p_match_id:form.dataset.matchId,p_difficulty:Number(data.get('difficulty')),p_satisfaction:Number(data.get('satisfaction')),p_repeat_intent:data.get('repeatIntent')==='on',p_note:String(data.get('note')||'')||null});message='경기 후 피드백을 저장했습니다.';await loadState()}catch(e){message=String(e?.message||e)}finally{busy=false;render()}}
function recommendPanel(){const items=recommendation?.ranked||[];return `<section class="fm-beta-panel fm-beta-growth-panel"><div class="fm-beta-panel-head"><div><h2>실제 경기 AI 탐색</h2><p>AI는 조건만 해석하고, 순위는 Supabase 실제 경기 데이터로 결정합니다.</p></div><span class="fm-beta-growth-chip">Live catalog</span></div><form class="fm-beta-growth-search" data-growth-form="recommend"><input name="query" maxlength="240" placeholder="예: 수원 영통 MF 중급, 저녁 8시 이후" aria-label="실제 경기 AI 검색"><button class="fm-beta-button fm-beta-button--primary" ${busy?'disabled':''}>${busy?'처리 중':'찾기'}</button></form>${message?`<div class="fm-beta-note" style="margin-top:10px">${esc(message)}</div>`:''}${recommendation?`<div class="fm-beta-growth-results"><p class="fm-beta-growth-reply">${esc(recommendation.result.reply)}</p>${items.length?items.slice(0,5).map(({m,reasons},i)=>`<article class="fm-beta-growth-result"><b>${i+1}. ${esc(m.title)}</b><span>${esc(startLabel(m.starts_at))} · ${esc(m.venue_name||m.area_label||'')}</span><small>${esc(reasons.join(' · ')||'실제 경기 조건 일치')}</small></article>`).join(''):'<div class="fm-beta-empty">현재 실제 공개 경기 중 조건에 맞는 경기가 없습니다.</div>'}</div>`:''}</section>`}
function waitlistPanel(){if(!accessToken())return'';const p=profile?.position||'';const list=matches.filter(m=>p&&['open','full'].includes(m.status)&&new Date(m.starts_at)>new Date()&&(m.status==='full'||Number(m.remaining_spots)<=0||slotLeft(m,p)<=0));return `<section class="fm-beta-panel fm-beta-growth-panel"><div class="fm-beta-panel-head"><div><h3>대기 신청</h3><p>취소로 ${esc(p||'선호 포지션')} 자리가 나면 신청 순서대로 자동 참가 전환됩니다.</p></div></div>${!p?'<div class="fm-beta-empty">프로필에서 선호 포지션을 설정해주세요.</div>':list.length?list.map(m=>{const q=queued(m.id);return `<div class="fm-beta-growth-row"><div><b>${esc(m.title)}</b><span>${esc(startLabel(m.starts_at))} · ${esc(POSITIONS[p]||p)}</span></div><button class="fm-beta-button ${q?'fm-beta-button--danger':''}" data-growth-action="${q?'cancel-waitlist':'join-waitlist'}" data-match-id="${esc(m.id)}" ${busy?'disabled':''}>${q?'대기 취소':'대기 신청'}</button></div>`}).join(''):'<div class="fm-beta-empty">현재 대기 대상 경기가 없습니다.</div>'}</section>`}
function historyPanel(){if(!accessToken())return'';const attended=participations.filter(p=>p.checked_in_at).map(p=>({p,m:matches.find(m=>m.id===p.match_id)})).filter(x=>x.m);return `<section class="fm-beta-panel fm-beta-growth-panel"><div class="fm-beta-panel-head"><div><h3>참석 이력 · 경기 후 피드백</h3><p>실제 체크인 기준 참석 이력과 완료 경기 피드백입니다.</p></div></div>${attended.length?attended.map(({p,m})=>{const f=savedFeedback(m.id);return `<div class="fm-beta-growth-history"><div><b>${esc(m.title)}</b><span>${esc(startLabel(m.starts_at))} · ${esc(p.position||'')}</span></div>${f?`<small>난이도 ${f.difficulty}/5 · 만족도 ${f.satisfaction}/5 · ${f.repeat_intent?'재참가 의향 있음':'재참가 의향 없음'}</small>`:m.status==='completed'?`<form class="fm-beta-growth-feedback" data-growth-form="feedback" data-match-id="${esc(m.id)}"><label>난이도<select name="difficulty">${[1,2,3,4,5].map(v=>`<option value="${v}" ${v===3?'selected':''}>${v}</option>`).join('')}</select></label><label>만족도<select name="satisfaction">${[1,2,3,4,5].map(v=>`<option value="${v}" ${v===4?'selected':''}>${v}</option>`).join('')}</select></label><label class="fm-beta-growth-check"><input type="checkbox" name="repeatIntent" checked> 다시 참가 의향</label><input name="note" maxlength="500" placeholder="선택 메모"><button class="fm-beta-button">피드백 저장</button></form>`:'<small>경기 종료 후 피드백을 남길 수 있습니다.</small>'}</div>`}).join(''):'<div class="fm-beta-empty">아직 체크인 완료된 실제 경기 이력이 없습니다.</div>'}</section>`}
function render(){const shell=root.querySelector('.fm-beta-shell');if(!shell)return;let host=shell.querySelector('[data-beta-growth-host]');if(!host){host=document.createElement('div');host.dataset.betaGrowthHost='true';shell.querySelector('.fm-beta-footer')?.before(host)}host.innerHTML=`<div class="fm-beta-growth-grid">${recommendPanel()}${waitlistPanel()}${historyPanel()}</div><div class="fm-beta-growth-live"><span class="fm-beta-growth-dot" data-state="${realtimeState}"></span>Realtime ${realtimeState==='connected'?'연결됨':realtimeState==='error'?'재연결 중':'연결 중'}</div>`}
function baseRefresh(){clearTimeout(refreshTimer);refreshTimer=setTimeout(()=>{root.querySelector('[data-action="refresh"]')?.click();loadState().catch(()=>{})},300)}
function connectRealtime(){if(!config||socket||document.visibilityState==='hidden')return;const url=config.url.replace(/^http/,'ws')+`/realtime/v1/websocket?apikey=${encodeURIComponent(config.publishableKey)}&vsn=1.0.0`;let ref=1;realtimeState='connecting';render();socket=new WebSocket(url);socket.onopen=()=>{socket.send(JSON.stringify({topic:'realtime:footmate-beta-growth',event:'phx_join',payload:{config:{broadcast:{self:false},presence:{key:''},postgres_changes:TABLES.map((table,i)=>({event:'*',schema:'public',table,id:i+1}))},access_token:accessToken()||config.publishableKey},ref:String(ref++)}));heartbeat=setInterval(()=>socket?.readyState===1&&socket.send(JSON.stringify({topic:'phoenix',event:'heartbeat',payload:{},ref:String(ref++)})),25000)};socket.onmessage=e=>{try{const d=JSON.parse(e.data);if(d.event==='phx_reply'&&d.payload?.status==='ok'){realtimeState='connected';render()}if(d.event==='postgres_changes')baseRefresh()}catch{}};socket.onclose=()=>{clearInterval(heartbeat);heartbeat=null;socket=null;realtimeState='error';render();clearTimeout(reconnectTimer);reconnectTimer=setTimeout(connectRealtime,2500)};socket.onerror=()=>{realtimeState='error';render()}}
root.addEventListener('submit',e=>{const f=e.target.closest('[data-growth-form]');if(!f)return;e.preventDefault();if(f.dataset.growthForm==='recommend')recommend(f);else submitFeedback(f)});
root.addEventListener('click',e=>{const t=e.target.closest('[data-growth-action]');if(!t)return;waitlistAction(t.dataset.matchId,t.dataset.growthAction==='cancel-waitlist')});
const observer=new MutationObserver(()=>{if(root.querySelector('.fm-beta-shell')&&!root.querySelector('[data-beta-growth-host]'))render()});observer.observe(root,{childList:true,subtree:true});
window.addEventListener('storage',e=>{if(e.key===SESSION_KEY){loadState().catch(()=>{});socket?.close()}});
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'){loadState().catch(()=>{});connectRealtime()}});
(async()=>{try{await loadConfig();await loadState();connectRealtime()}catch{realtimeState='error';render()}})();
}
